// Biscuit: a feral chaos dog. Squirrels, bins, socks, sniffing everything, zoomies at all times, a deep and unshakeable belief that the item boxes are
// snacks and every kart is a fetchable stick. Barks, sniffs and screams in equal measure; dog-crude at the very most. Clean (no swearing).
export default {
  welcome: ['WOOF! New friends! Sniff sniff! Are you snacks?', 'Hello hello hello! I ate a sock! Welcome!', 'Bork! Come in! Mind the bin! I am the bin!', 'Woof woof woof! Zoomies! Welcome!', 'Who is a good boy? ME! Always me! Woof!'],
  select_me: ['You picked me! I will eat your homework!', 'Woof! Best choice! I will fetch everything!', 'Me me me! I am the good boy! The chaos boy!', 'Yes! I am a menace and I love you!', 'Pick me! Pick me! I will wee on your tyres! Gently!'],
  gp_win: ['WOOF! Cup! Cup! I will bury it in the garden!', 'I won! Treats! Treats for all! Mostly me!', 'Champion dog! Bork bork bork!', 'The Cup! It is a bone! A big shiny bone!', 'I did it! Squirrel! Squirrel! Squirrel!'],
  photo_finish: ['So close! Squirrel-close! Woof!', 'Photo! Photo! Me! Look at my tongue!', 'By a whisker! I have many whiskers!', 'That was a sniff away! Woof!', 'Woof! My nose crossed first!'],

  start: ['Zoomies on the grid! Woof woof woof!', 'Everybody sniff each other! Race rules!', 'Eight karts! Seven sticks! One boy!', 'Woof! Is that a squirrel? No! Race!', 'Let me at it! Let me at ALL of it!'],
  ready: ['Ready ready ready! Tail is wagging!', 'Sniff sniff! Race! Snacks! Sniff!', 'Woof! My nose says GO!', 'I am ready! I have been ready since breakfast!', 'Sit! Stay! No! GO!'],
  go: ['WOOF! GO! RUN! ZOOMIES!', 'Bork bork bork! Go go go!', 'Fetch! Fetch! Fetch the finish line!', 'Squirrel! Squirrel! Squirrel! GO!', 'Walkies! Walkies! WALKIES!'],
  rocket_start: ['Woof! Fastest dog alive!', 'Zoomies! I am a sausage with a rocket!', 'Bork! I am so quick! So very quick!', 'I am a good dog! A fast dog! A chaos dog!', 'Whoosh! That was my tail! Whoosh!'],
  bad_start: ['Woof... I forgot what I was doing.', 'Squirrel! Oh. We were racing. Oops.', 'I was sniffing a bin. Sorry.', 'Slow start! I ate the clutch!', 'Ow, I tripped on my ears!'],
  boost: ['ZOOMIES! WOOF WOOF WOOF!', 'Fast fast fast fast fast!', 'My legs are blurry! Woof!', 'Boost! I ate a firework!', 'Wheee! I am a rocket with a tail!'],
  speed: ['Fastest boy! Fastest dog! Woof!', 'Zoomies activated! Do not look at the bin!', 'I am so fast I forgot where I was going!', 'Bork! Look at my ears flap!', 'My tongue is out and I cannot put it back!'],
  drift: ['Sliding! Like on a wet floor! Woof!', 'Wheeee! Sideways! Like a sausage!', 'I am chasing my own tail! Round and round!', 'Bork! Corner! Corner! Corner!', 'Zoom! Skid! Sniff!'],
  mini_turbo: ['Woof! A little zoom!', 'Zoomy zoomy!', 'Tiny zoomies! Woof!', 'Boop! Fast!', 'Bork! A treat for my legs!'],
  max_charge: ['MAXIMUM ZOOMIES! WOOF!', 'I am so full of zoom!', 'Squeak! I am glowing! Squirrel!', 'Full tail! Full speed! Full bin!', 'My whole body is a zoom!'],
  overtake: ['Sniff ya later, {other}!', 'Woof! Passing {other}! Smell ya!', 'Bork! Out of my way, {other}! I am chasing a stick!', '{other}! I am faster than you! And I smell better!', 'Wheee! Bye, {other}! I love you! Bye!', 'Woof! {other}, your bum smells slow!'],
  overtaken: ['{other}! You stole my stick!', 'Woof! {other}, come back! I want to sniff you!', 'Grr! {other}! That was MY lane!', 'Bork! {other}, I will chew your tyres!', 'No no no, {other}! Squirrel! Squirrel!', '{other}! Play fair! Or at least fetch!'],
  take_lead: ['I am first! Fetch me a trophy!', 'Woof! I am the leader of the pack!', 'Number one dog! Best dog! Boy!', 'Look at me! Look at me! I am in front!', 'First! I am so good!'],
  lose_lead: ['Woof... somebody took my stick.', 'Whimper! I was first!', 'I will chase them! Bork!', 'My lead! Come back, lead!', 'Aww. I wanted that one.'],
  hit: ['YELP! My bum!', 'Whimper! That was rude!', 'Ow ow ow! Tail! Ears! Everything!', 'Woof! That hurt my feelings!', 'Squeak! Why?!', 'I am not a chew toy! Ow!'],
  hit_by_item: ['Who threw that?! Come here, I will sniff you!', 'Bork! That is not a stick!', 'Grr! Not fair! I was being good!', 'Woof! I will bite your item!', 'Ow! I was only barking!'],
  hit_kernel_panic: ['Woof! The thing broke! The thing broke!', 'Panic! Everybody panic! Woof!', 'Bork! The computer is sad!', 'It crashed! I sat on it!', 'Whimper! The machine ate my squeaky toy!'],
  hit_bsod: ['Blue! Everything is blue! Woof!', 'The sky fell on me! Whimper!', 'Blue screen! I do not like blue!', 'Woof woof! The screen is a squirrel!', 'Bork! It is stuck! Fix it!'],
  hit_popups: ['Too many windows! Squeak!', 'Bork! Go away, adverts! I cannot see my ball!', 'Pop-ups! Pop-ups! Pop-ups!', 'Whimper! The ads are chasing me!', 'Woof! Close them! Close them with a bite!'],
  hit_shrink: ['I am tiny! Like a puppy again! Woof!', 'Squeak! I am so small!', 'Tiny dog! Mini boy!', 'Woof! Everything is a giant sock!', 'I can fit in a bin now! Yay!'],
  hit_spill: ['Slippery! Slidey! Whee!', 'Woof! A puddle! I love puddles!', 'Someone spilled it! I will lick it!', 'Wet paws! Wet paws!', 'Bork! I slid on my belly!'],
  hit_zeroday: ['BOOM! Squeak! Hide under the sofa!', 'Woof! Loud noise! Loud noise! Loud!', 'Bork! Who threw a firework?!', 'Whimper! The bang!', 'I need to hide! In a bin!'],
  hit_pigeon: ['PIGEON! WOOF! PIGEON! WOOF!', 'A bird! A bird! My arch-enemy!', 'Bork! That bird has a face!', 'Woof! I will chase it forever!', 'Squeak! Pigeons are my nemesis!'],
  item_get: ['Present! Present! Is it a ball?', 'Woof! Treats! Treats! Treats!', 'A snack! A snack! Not a snack?', 'Sniff sniff! What is it?', 'Bork! I got something!'],
  item_use_attack: ['Fetch it, {other}! FETCH!', 'Woof! For you, {other}! A present!', 'Take it, {other}! It is a bone!', 'Bork! I made this for you, {other}!', 'Squeak! Sniff THIS, {other}!'],
  item_use_defence: ['Shield! Woof! I am a turtle dog!', 'Protected! Snug! Woof!', 'Hide! Hide! Hide!', 'Bork! I am an armadillo now!', 'Nobody can touch my bone!'],
  item_hit_rival: ['Got you, {other}! Good boy me!', 'Woof! {other}, caught you!', 'Bork! That one was for {other}!', 'Fetch, {other}! You did not fetch!', 'I hit {other}! Treat please!'],
  miss: ['Aww. It rolled away.', 'Woof! Where did it go?', 'I missed! I missed! Where is it?', 'Bork! Sorry!', 'Whimper! I lost the stick!'],
  dodged: ['Ha! You cannot catch ME!', 'Woof! Too slow!', 'I ducked! Like a duck! Quack! No, woof!', 'Bork! Missed me!', 'Squeak! Faster than a squirrel!'],
  block: ['Woof! Nope!', 'Bork! Not today!', 'My shield! My lovely shield!', 'Block! Block! Block!', 'I am a good wall!'],
  wall: ['Ow! My nose! My nose!', 'Woof! The wall is not a ball!', 'Bonk! That was a bonk!', 'Whimper! Wall bad!', 'I licked it! It was not a treat!'],
  fall: ['Weeeee! Down I go!', 'Woof! Wheeeee! Oh no!', 'Falling! Squeak! Falling!', 'I am a flying dog! Briefly!', 'Whimper! I want my mum!'],
  respawn: ['Back! Woof! Miss me?', 'I am back! Bork bork!', 'New dog! Same boy!', 'Boing! I am here!', 'I have returned! I am hungry!'],
  offroad: ['Grass! I love grass!', 'Woof! Mud! Mud! Mud!', 'Sand! I will dig a hole!', 'Off the road! Time to sniff!', 'Wheee! I found a stick!'],
  jump: ['Wheeeee! I am flying!', 'Woof! Up up up!', 'Bork! I jumped over a bin!', 'Fly, dog, fly!', 'I am a bird! Woof! No!'],
  trick: ['Look! I did a trick! Treat?', 'Woof! A somersault! Treat please!', 'Spin! Spin! Spin! Roll over!', 'Bork! I am so clever!', 'Treats! For tricks! Hello?'],
  shortcut: ['Shortcut! I smelled it!', 'Woof! A secret hole!', 'Bork! I dug a tunnel!', 'Shh! I will bury this route!', 'A secret! Do not tell the squirrel!'],
  near_miss: ['Whoa! Woof!', 'Squeak! That was a close sniff!', 'Phew! My tail!', 'Bork! That almost got me!', 'Woof! My heart goes boing!'],
  wrong_way: ['Woof? Where is the finish?', 'Bork! This is the wrong way! Smells nice, though!', 'I am going backwards! Woof!', 'Squeak! Is the world upside down?', 'I turned around to chase my tail!'],
  last_place: ['Woof... last. Sniff.', 'I am at the back. I smell everyone!', 'Last! I will bite them all!', 'Bork! Wait for me!', 'The best view is from behind. Of bums.'],
  comeback: ['I am coming! Woof!', 'Bork! Chasing! Chasing! Chasing!', 'Faster, legs, faster!', 'I will catch them! I am a good boy!', 'Squirrel mode activated!'],
  lap2: ['Second lap! Walkies again!', 'Woof! More! More!', 'Lap two! Zoomies again!', 'Bork! Still running! Still good!', 'Two laps! I counted! One two! Woof!'],
  final_lap: ['LAST LAP! WOOF WOOF WOOF!', 'Final lap! Do not stop! Do not sniff!', 'Bork! One more! Hurry!', 'Last lap! Treat soon! Treat soon!', 'WOOF! Finish it! Finish it!'],
  finish_win: ['I WON! TREATS! TREATS! TREATS!', 'Champion dog! Woof! Cuddles!', 'First! Good boy! Best boy!', 'Bork! I am the best! Give me a biscuit!', 'I won! Squirrel party! Squirrel party!', 'Winner! Winner! Dinner! Dinner!'],
  finish_podium: ['Podium! I did a good boy!', 'Woof! Shiny! I want to chew it!', 'Third place! Still a good boy!', 'Treat? Is there a treat?', 'I am on a box! Woof!'],
  finish_lose: ['Woof... can I have a cuddle?', 'Sniff. It is fine. I ate a sock.', 'Whimper. I wanted a trophy.', 'Bork! Next time! I will win!', 'I did my best! I am a good boy!', 'Aww. Treat anyway?'],
  taunt: ['Sniff my bum! I am winning!', 'Bork! Come get me!', 'You are all so slow! Woof!', 'Woof! I am the best at racing!', 'Chase me! Chase me!', 'I have your sock! Come and get it!'],
  quip: ['I ate a sock this morning. Fine.', 'Who put a hat on a man in the race? I love him.', 'Is that a squirrel? No? Aww.', 'No wee since Tuesday. This is a crisis.', 'I sniffed a bin. It was beautiful.', 'WHO IS A GOOD BOY? ME! ALWAYS ME!', 'My tongue fell out. It lives outside now.', 'I love everyone. I might bite you all, gently.', 'I licked the wall. Do not ask. It was nice.'],

  bump: ['Woof! Sorry, {other}! Sniff!', 'Bork! Bumped you, {other}! Tag!', 'Oops, {other}! I smelled you!', 'Sniff! Hello, {other}! Boop!', 'Boop! {other}! Play with me!'],
  bumped: ['Ow, {other}! Bad boy!', 'Grr, {other}! I bite!', '{other}! You are on my lead!', 'Woof! {other}! Watch my tail!', 'Whimper! {other}! You boop me too hard!'],
  trick_fail: ['Woof... I fell over.', 'Oops! Tripped on my ears!', 'Bork! I did it wrong!', 'Squeak! Not a trick!'],
  perfect_release: ['Woof! Perfect!', 'Bork! A good boy!', 'Zoom! Right on time!', 'Treat please! That was perfect!'],
  vs: {
    marco: ['Marco! Walkies? Walkies? Walkies?', 'Teacher! Sit! No, YOU sit! Woof!', '{other}! Throw the clipboard! Fetch!', 'Marco! Whistle! Whistle! I love it!'],
    subnet: ['Sir Subnet! I will bury your beans!', 'Subnet! Throw the stick! The big stick!', '{other}! Your armour is crunchy!', 'Subnet! I will guard your bunker! With my teeth!'],
    lambda: ['Sadie! Coffee! Coffee! Share! Share!', 'Sadie! You are as zoomy as me!', '{other}! I love your shouting! Shout more!', 'Sadie! Join my cult! The bin cult!'],
    packet: ['Pete! Is there a drone? Where? Where?', 'Packet! Throw the parcel! Fetch!', '{other}! I will protect you from the cones!', 'Pete! You smell like a postman! I love postmen!'],
    carlos: ['Carlos! Coconut! Coconut! Coconut!', 'Carlos! Beach! Sand! Dig dig dig!', '{other}! I love your flip-flops! Chew chew!', 'Carlos! You smell like the sea!'],
    tilly: ['Tilly! Biscuit? Biscuit? Is it a biscuit?', 'Dame Tilly! I love your hat! Can I chew it?', '{other}! Pat me! Pat me!', 'Tilly! You smell of tea and sadness!'],
    rex: ['Rex! Beep boop! I love you! Beep!', 'Rex! Fetch the planet!', '{other}! You are shiny! Can I chew you?', 'Rex! Your terms are delicious!'],
  },
};
