// Biscuit, rude banter: a golden spaniel with the vocabulary of a sailor and the impulse control of a sock. Squeaky, feral, completely unashamed. Dog-crude only (bins, bums, socks, wee), no targeting of anyone real.
export default {
  welcome: ['BORK! Hello, you absolute sods!', 'Woof! Who is a good boy? Not me! I ate a sock!', 'Hello! Smell my bum! No, smell yours!'],
  select_me: ['PICK ME! I AM A GOOD BOY AND A BASTARD!', 'Yes! Me! I am going to wee on everything!', 'Woof! Finally! Somebody with taste and treats!'],
  gp_win: ['I WON THE CUP! I AM GOING TO ROLL IN SOMETHING DEAD!', 'Bork! Champion! Bring me ALL the sausages!', 'Cup! Mine! I am going to bite it!'],
  photo_finish: ['That was close! I nearly wet myself! I did!', 'Photo finish! Somebody give me a treat or a sedative!'],
  start: ['Race! Race! I have to wee! Race!', 'Zoomies! Zoomies! Zoomies, you absolute wankers!', 'Who is that? Who is THAT? Everyone! Fight!', 'I have a sausage in my kart. Do not look.'],
  go: ['GO GO GO BORK BORK, YOU MUPPETS!', 'ZOOMIES! Piss off, everyone!', 'Woof woof WOOF! Get out of my way!', 'Squirrel! No! GO!'],
  rocket_start: ['ZOOM! I AM A BULLET WITH EARS!', 'Bork! That was bloody brilliant!', 'Woof! I beat you all! Sniff my exhaust!'],
  bad_start: ['I got distracted by a bum! Bollocks!', 'Stalled! Sausage! I mean, sorry!', 'Woof. Not woof. Fuck.', 'Was looking at a leaf. Damn it.'],
  boost: ['BOOST! I AM A FLYING SAUSAGE!', 'WHEEEE! My ears are flapping, you tossers!', 'Faster than a squirrel on fire!', 'Zoom zoom zoom! Bark bark! Oh, bollocks, faster!'],
  speed: ['ZOOMIES! Cannot feel my bum!', 'Flat out! Tongue out! Everything out!', 'I am a dog on a mission! A very sweary one!'],
  drift: ['Sideways! Like a dog on a polished floor!', 'Wheeee! Slippy! Slippy!', 'I am sliding! I love sliding! I hate sliding!'],
  mini_turbo: ['Woof! Burst! More!', 'Bork! Little bit of zoom!'],
  max_charge: ['MAXIMUM ZOOM! BRACE YOUR BUMS!', 'Full charge! I might explode! Arse first!'],
  overtake: ['BYE, {other}, YOU LUMP!', 'Sniff my tail, {other}, you tit!', 'Passing {other}! Smell ya later, you knob!', 'Woof! {other}, I am a dog in a hurry!', 'Out of my way, {other}! Bork bork!', '{other}! Move your arse! I am going to bite it!'],
  overtaken: ['OI! {other}! I WILL BITE YOU!', 'Bark! {other}, you arse! Bark!', '{other} PASSED ME! I am going to wee on your tyres!', 'Growl! Bastard {other}!', '{other}! That was my road! MY ROAD!'],
  take_lead: ['I AM FIRST! I AM A GOOD BOY AND A LEADER!', 'Bork! Front! Front! I am front, you sods!', 'Leader! Give me a treat, you wankers!'],
  lose_lead: ['Whining! Whining! Who took my lead?!', 'My lead! Bring it back or I will bite your leg!', 'Woof! No! Bollocks! Lost!'],
  hit: ['YELP! Bastard!', 'Ow ow ow! My bum! My bum!', 'Whimper! That hurt my feelings and my arse!', 'Bark! Who did that?! I will wee on you!', 'Squeak! Ow! Fuck!'],
  hit_by_item: ['WHO THREW THAT? I WILL BITE YOU!', 'Bork! That was MY leg!', 'I smell you! It was YOU! I am going to wee on you!', 'Growl! I will find you and lick you! Angrily!'],
  hit_kernel_panic: ['Kernel panic! I am a little dog in a big crash!', 'Whimper! The machine is broken! Bollocks!'],
  hit_bsod: ['Blue screen! Who broke the telly?!', 'Woof! The screen is blue! Who did that?!'],
  hit_popups: ['Adverts! Bark at the adverts!', 'Stop popping! I hate popping!'],
  hit_shrink: ['I AM TINY! I AM A TINY TINY DOG!', 'Squeak! Shrunk! Everything is enormous! Bollocks!'],
  hit_spill: ['Spilled! Oh! I will lick it! Wait, no!', 'Slippery! Whee! No! Ow!'],
  hit_zeroday: ['Mine! Bang! I peed a bit!', 'Zero-day! I do not know what that is! I am scared!'],
  hit_pigeon: ['PIGEON! I HATE PIGEONS! BORK!', 'Bird! In my face! Bark! I will eat you, bird!'],
  item_get: ['PRESENT! OH! OH! I WILL BITE IT!', 'Item! Treat! Not a treat! Fuck!', 'Woof! Shiny! Someone is getting bitten!', 'I got one! Give me a cuddle! Or else!'],
  item_use_attack: ['TAKE THAT, {other}, YOU KNOB!', 'Bork! For you, {other}! With love!', 'Woof! Fetch, {other}! Fetch THAT!', 'Sniff THIS, {other}!', 'Bad {other}! Bad! Nobody likes you!'],
  item_use_defence: ['SHIELD! Try and bite me NOW!', 'I am protected! Nobody touches my bum!', 'Woof! Go away, everyone!'],
  item_hit_rival: ['GOT YOU, {other}! WHO IS A GOOD BOY? ME!', 'Bork! Bullseye! {other} is a sausage!', '{other}! Hit! Hit! Whoo!', 'Woof! Right in the bum, {other}!'],
  miss: ['Missed! Bollocks! Woof!', 'I missed! Whine! Somebody throw it again!', 'Aargh! Where did it go? I want it back!'],
  dodged: ['HA! MISSED! I AM A GOOD BOY AND A SLIPPERY ONE!', 'Nope! You cannot catch me, sausage-brains!', 'Bark! Dodge! Dodge!'],
  block: ['BLOCKED! Nobody bites me!', 'Woof! Not today, you knobs!', 'No! Bad! Away!'],
  wall: ['OW! Wall! Bad wall! I will wee on you!', 'Bork! Who put that there?!', 'Nose! My nose! My nose!'],
  fall: ['FALLING! I AM FALLING! BORK BORK BORK!', 'Down! Down! Everyone is tiny! Whee! No!', 'Yelp! Void! Bad void!', 'Falling! Squeak! I did a wee!'],
  respawn: ['Back! I am back! I am a good boy!', 'Reborn! Bork! Sniff me!', 'Woof! I missed you! And your bums!'],
  offroad: ['GRASS! I LOVE GRASS! ROLLING TIME!', 'Sand! Sand! Sand! In my bum!', 'Off road! Woof! Dig dig dig!'],
  jump: ['FLYING! I AM A BIRD WITH EARS!', 'Wheee! Up! Up! Down! Oh dear!', 'Airborne! Woof! Bollocks!'],
  near_miss: ['Bork! Nearly! My bum nearly!', 'Close! Close! I nearly had a wee!', 'Phew! Sniff sniff! Safe!'],
  wrong_way: ['Backwards! Why? I do not know! Woof!', 'The road is upside down! Bork!', 'I am going the wrong way. Squirrel!'],
  last_place: ['LAST! But I am still a good boy!', 'Bottom of the pack! I did not do that on purpose!', 'Last! Whimper! And a bit of a wee!'],
  comeback: ['Coming for you! Bork! Bork! BORK!', 'Zoomies! Catch-up zoomies!', 'Watch me chase you! I love chasing!'],
  lap2: ['Lap two! Zoomies two!', 'Second lap! Woof woof! I need a wee!'],
  final_lap: ['LAST LAP! BITE EVERYONE!', 'Final lap! Bork! I am a bullet!', 'Last lap! Give me ALL the treats!'],
  finish_win: ['I WON! BUY ME A STEAK! A WHOLE STEAK!', 'First! I am a good boy and a champion!', 'Bork! Victory! I am going to roll in something!'],
  finish_podium: ['Podium! I will chew the trophy!', 'Top three! Treats! Treats! Treats!', 'Woof! Shiny! I love it! Give me a biscuit!'],
  finish_lose: ['I lost! Whimper! I ate a sock!', 'Bork. Not good. Bad day. Good bum.', 'Woof. I want my bed. And a sausage.'],
  taunt: ['Faster! You are slower than a tortoise in a coma!', 'Bork! Come on, you lumps!', 'I have smelled your bum! It is slow!', 'You drive like a cat! A sad cat!', 'Woof! Keep up, you sausages!'],
  quip: ['I ate a sock this morning. No regrets.', 'Who put a man in a hat in the race? I love him.', 'Is that a squirrel? No? Bollocks.', 'I have not had a wee since Tuesday. Panic.', 'I sniffed a bin. It was lovely.', 'WHO IS A GOOD BOY? NOT ME! I AM A MENACE!', 'My tongue is out. I cannot put it back.', 'I love everyone. And I will bite you all.', 'Sometimes I lick the wall. Do not ask.', 'Where are we? Who am I? Sausage!'],
  roast: ['{other}! You drive like a sack of bricks!', 'Bark! {other}, you are rubbish!', '{other}! Learn to steer, you lump!', 'Woof! {other} smells of disappointment!', '{other}, your driving makes me sad. And wee.'],
  bump: ['Woof! Sorry, {other}! Not sorry!', 'Oops, {other}! I bumped you! Hehe!', 'Nudge nudge, {other}!'],
  bumped: ['OI, {other}! I will bite your tyre!', 'Bark! Off! Off me, {other}!', '{other}! That was MY bumper!'],
  perfect_jump: ['PERFECT! I AM A BIRD! A GOOD BIRD!', 'Woof! Landed it! Treat!'],
  swap_item: ['Swapped! Shiny! Mine!', 'Bork! Switch! I love it!'],
  double_item: ['TWO! I got TWO! Woof!', 'Double! Bork! I will bite someone!'],
  class_select: ['{class} Mbps? I do not know what that is! ZOOM!', '{class} Mbps! Bork! It is a big number!', '{class} Mbps! Woof! Somebody is going to lose!'],
  jump_vehicle: ['I jumped a lorry! Bork!', 'Over the bus! I am the best dog!'],
  vs: {
    marco: ['Marco! Give me a treat! And a hug! And your shoe!', '{other}! Hello! I love you! Bark!', 'Marco! You smell of tea and bum!'],
    subnet: ['Sir Subnet! Take off the tin! I want to bite it!', '{other}! You clank! Clank clank!', 'Subnet! I will wee on your plume!'],
    lambda: ['Sadie! You are a squeaky toy! Squeak!', '{other}! You are loud! I am louder! BORK!', 'Sadie! I hate your hoodie and want to chew it!'],
    packet: ['Pete! Give me the parcel! Give it! Bark!', '{other}! I will bite your parcel!', 'Pete! You smell of cardboard and lies!'],
    carlos: ['Carlos! You smell of limes and naps! I love it!', '{other}! Stop being slow! Chase me!', 'Carlos! Wake up and scratch my belly!'],
    tilly: ['Tilly! Scary! Scary! Give me a biscuit!', '{other}! I am going to sniff your handbag!', 'Tilly! You smell of gin and trouble!'],
    rex: ['Rex! Clanky! Growly! I love you! Bite!', '{other}! Metal man! I am going to wee on you!', 'Rex! You have no bum! How do you sit?'],
  },
};
