// Caipirinha Carlos, versão grosseira (só com "Rude banter" ligado): português do Brasil (pt-BR) e NADA além disso. O vendedor de praia queimado de sol,
// maluco de pedra, dono imaginário da orla inteira: xinga em português (porra, caralho, merda, cacete), ameaça a freguesia com coco e isopor, cobra
// pedágio de todo mundo e só pensa em caipirinha e futebol. Sem ofensas a ninguém de verdade: o exagero é de desenho animado.
export default {
  welcome: ['Chega aí, seus folgados! A praia é minha, porra!', 'Bem-vindos ao inferno do Carlos! Pedágio em coco!', 'Sentem aí, otários, e peçam a caipirinha!', 'Fala, seus trouxas! Quem pisar na minha toalha leva isopor na cara!'],
  select_me: ['Escolheu o Carlos? Agora é meu escravo da areia, porra!', 'Boa, caralho! Agora me paga uma caipirinha!', 'Sabia que você ia me escolher, seu trouxa!'],
  gp_win: ['A taça é minha, seus babacas! Vão trabalhar pra mim!', 'Campeão, caralho! Todo mundo me deve uma caipirinha!', 'Ganhei a copa e nem suei! Bom, suei. Sempre!'],
  photo_finish: ['Que merda, foi por um limão! Meu coração parou!', 'Quase, caralho! Meu isopor quase me matou!', 'Foto-finish, porra! Minha sunga rasgou!'],
  start: ['Anda logo, seus lerdos! O sol tá queimando!', 'Tá pronto? Eu não! Mas dane-se!', 'Quem chegar por último lava meu isopor, porra!', 'Corrida na minha praia, é? Pagando pedágio, otários!'],
  go: ['BORA, SEUS BABACAS! A areia é minha!', 'Vai, vai, vai, caralho! Cobrança na linha!', 'Partiu! Quem não correr vira farofa!', 'Porra, acelera! O limão tá esquentando!'],
  rocket_start: ['Haha! Largada de foguete, seus lerdos! Tchau!', 'Saí que nem coco ladeira abaixo, porra!', 'Voei! Chupa, seus preguiçosos!'],
  bad_start: ['Porra! Eu estava olhando um passarinho!', 'Parei, caralho! Culpa do calor! E do isopor!', 'Merda! Estava mexendo na caipirinha!', 'Caralho, travou! Eu estava no quiosque!'],
  boost: ['Aí, porra! Meu chinelo tá saindo voando!', 'Turbo, caralho! Alguma coisa pegou fogo!', 'Zum! Isso é um absurdo, mas é bom!', 'Voando! Meu isopor virou foguete!'],
  speed: ['Velocidade! Meu cabelo virou outra coisa!', 'Voando baixo, caralho! O limão voou!', 'Que rápido! Minha bunda está vibrando!'],
  drift: ['Derrapando, porra! Igual manteiga em frigideira quente!', 'De lado, tipo caranguejo! Mas sóbrio!', 'Drift, caralho! Não olha!'],
  mini_turbo: ['Chutinho na bunda, porra!', 'Explodiu! Senti nos chinelos!', 'Zoom, seus lerdos!'],
  max_charge: ['Carga máxima, caralho! Sente o cheiro de limão!', 'Força total, porra! Quero ver quem aguenta!'],
  overtake: ['Com licença, {other}, seu lerdo do caralho!', 'Tchau, {other}! Dá tchau pra minha bunda!', 'Passando, {other}! Foi mal! Mentira, não foi!', '{other}, você dirige igual caracol de chinelo!', 'Sai da frente, {other}, porra! Tenho uma praia pra cuidar!', '{other}, anda logo, merda!'],
  overtaken: ['Ah, porra, {other}! Seu babaca!', '{other}, cara, isso é falta de respeito! Vou falar pro mar!', 'Eu deixei, {other}! Foi educação! Mentira, caralho!', '{other}! Seu coco do inferno!', 'Tá, {other}. Pode passar. Vou tirar uma soneca.'],
  take_lead: ['Primeiro, porra! Me tragam uma cadeira!', 'Estou na frente! Estou nervoso! Me dá uma caipirinha!', 'Na frente! Olha eu! Sou o deus do limão!'],
  lose_lead: ['Eu estava em primeiro! Agora sou um limão triste!', 'Porra! Quem roubou a minha liderança?', 'Liderança perdida! Hora da caipirinha, caralho!'],
  hit: ['Porra! Bem na bunda!', 'Ai, cara! O cabelo não!', 'Aiii! Isso doeu nos meus sentimentos!', 'Caralho, isso ardeu! Muito!', 'Estou bem. Mais ou menos. Meus óculos, não!'],
  hit_by_item: ['Quem jogou isso? Vem cá que eu te abraço! Forte!', 'Isso não foi tranquilo, porra! Nada tranquilo!', 'Estou puto! Estou puto devagar!', 'Alguém vai levar um coco na cabeça!'],
  hit_kernel_panic: ['Kernel panic, caralho! Meu cérebro foi pro mar!', 'Porra, a máquina está chorando!'],
  hit_bsod: ['Tela azul? Igual minha praia, mas quebrada, merda!', 'Tá tudo azul, porra!'],
  hit_popups: ['Propaganda, caralho! Tanta! Que desrespeito!', 'Para com os anúncios! Estou de férias, porra!'],
  hit_shrink: ['Estou pequeno, caralho! Os limões estão enormes!', 'Encolhi! Meu chinelo virou canoa, porra!'],
  hit_spill: ['Minha bebida! Alguém derramou minha caipirinha, caralho!', 'Escorregando! Porra! Alguém me seca!'],
  hit_zeroday: ['Zero-day? Eu não tinha nenhum dia, porra! Zero!', 'Uma mina! Quem faz isso, caralho?!'],
  hit_pigeon: ['Um pássaro na minha cara! O mar está bravo!', 'Cocô de pombo, caralho! Isso dá sorte? Dá nada!'],
  item_get: ['Ooh, um presente. Alguém vai chorar!', 'Item, porra! Vamos causar um drama!', 'Um presente! Pros deuses do calçadão!', 'Peguei uma coisa e não é protetor solar!'],
  item_use_attack: ['Toma, {other}, seu lerdo!', 'Pega, {other}, cara! Te amo! Com força!', 'Acorda, {other}, seu coco do caralho!', 'É pra você, {other}! Não é um abraço!', 'Porra, vai, vai, acerta esse babaca!'],
  item_use_defence: ['Protegido, seus otários! Vem tentar!', 'Escudo ligado, caralho! Quero ver agora!', 'Ninguém encosta em mim! Nem a lei!'],
  item_hit_rival: ['Acertei, {other}, seu otário!', 'Gol, porra! Direto em você, {other}!', 'Toma, {other}! Isso é por pisar na minha toalha!', 'Na mosca, {other}! Bem na bunda!', '{other}! Levou isso e a tua mãe também!'],
  miss: ['Merda, errei! Culpa do sol!', 'Errou, caralho! A mira estava mole!', 'Porra, o item é um covarde!'],
  dodged: ['Errou, seu babaca! Nem chegou perto!', 'Ha! Nem me viu, porra!', 'Passou raspando, caralho! Que susto!'],
  block: ['Bloqueado, seus otários!', 'Não, caralho! Isso aqui não é de graça!', 'Bloqueei, porra! Tenta de novo!'],
  wall: ['Porra, a parede! Quem colocou isso aí?', 'A parede, caralho! Vou processar o pedreiro!', 'Bati! Um muro nojento!'],
  fall: ['Caí, porra! Fui pro mar!', 'Caralho, que queda! Meu isopor!', 'Desci pra água, merda! Volto já!', 'Socorro! Quer dizer, vão à merda! Socorro!'],
  respawn: ['Voltei, seus babacas! Sentiram falta?', 'Renasci, caralho! Com mais raiva!', 'Estou de volta, porra! Cadê meus pedágios?'],
  offroad: ['Areia, porra! Isso aqui é minha casa!', 'Merda, fora da pista! Mas gosto de areia!', 'Areia no kart, caralho! Isso é intimidade demais!'],
  jump: ['Voando, caralho! Igual papagaio bêbado!', 'Ha! O chão me odeia, porra!', 'No ar! Tchau, gravidade, sua otária!'],
  near_miss: ['Por pouco, porra! Meu coração virou farofa!', 'Caralho, quase! Meus intestinos abdicaram!', 'Ufa, merda! Meu limão quase caiu!'],
  wrong_way: ['Direção errada? O errado é o mundo, caralho!', 'Alguém mudou a praia! Vou processar o responsável!', 'Estou indo pro lado errado de propósito, seus lerdos!'],
  last_place: ['Último, porra! Que vergonha! Vou raspar a sunga!', 'Estou lá atrás, mas ainda sou melhor que todos vocês!', 'Último lugar! Isso é falta de respeito com meu império!'],
  comeback: ['Estou subindo, caralho! E vou comer todo mundo!', 'Olha eu subir, seus preguiçosos!', 'A volta do rei! Se escondam, seus covardes!'],
  lap2: ['Segunda volta! Mais porcaria, mais sol!', 'Volta dois, caralho! Meus joelhos são velhos!'],
  final_lap: ['Última volta! Caiam, seus nobres de araque!', 'Última volta! Dane-se a honra, quero ganhar!', 'Volta final! Vou morrer pela glória! Ou por uma caipirinha!'],
  finish_win: ['Vitória! A praia inteira é minha, porra!', 'Ganhei, caralho! Me tragam uma cadeira e uma cerveja!', 'Primeiro! Suas mães vão ficar sabendo!'],
  finish_podium: ['Pódio! Um pedaço de lata brilhante! Maravilha!', 'Não foi o primeiro, mas quase, seus otários!', 'Pódio! Me traz uma caipirinha, escravo!'],
  finish_lose: ['Derrota! Vou chorar na minha barraca!', 'Perdi, caralho! Pelo cacete do futebol!', 'Desonra! Vendam meu isopor e meu guarda-sol!'],
  taunt: ['Você é lento, seu verme!', 'Mais rápido, seus caranguejos manetas!', 'Anda logo, seus sacos de farofa!', 'Esse jeito de dirigir é um crime contra a praia!', 'Se você diminuir a velocidade mais uma vez, para de vez, seu doido!'],
  quip: ['Alguém trouxe sanduíche? Um siri comeu o meu.', 'Eu dividi uma pizza em fatias de /26. A pizza chorou.', 'Tem 254 hosts em uma /24 e eu odeio 253.', 'Estou quarenta por cento areia e sessenta por cento raiva.', 'Os produtores estão olhando? Alô, seus babacas!', 'Eu cobrei pedágio do mar. Ele me deve cem.', 'Alguém quer picolé? Vendo por dois pedaços de dignidade!', 'Esse calçadão é uma vergonha. E é meu. Porra!'],
  roast: ['{other}, você dirige igual a um bêbado em dia de chuva!', 'O seu kart é uma cena de crime, {other}!', 'Um jegue dirige melhor, {other}, e cheira melhor!', '{other}, aprende a dirigir, seu doido!', 'Que vergonha, {other}! Até o isopor desviaria!'],
  bump: ['Sai, {other}, seu cabeça de coco!', 'Um empurrãozinho, {other}! Sentiu? Otário!', 'Chega pro lado, {other}, ou eu te taxo!'],
  bumped: ['Como ousa, {other}?! Seu babaca!', 'Arranhou meu kart, {other}! Vai pagar o pedágio!', '{other}, eu vou pegar o teu isopor!'],
  perfect_jump: ['Pulo perfeito, seus lerdos!', 'Decolei que nem coco pro alto!'],
  swap_item: ['Troquei! E você nunca vai saber por quê!', 'Mudei! Esperto, caralho!'],
  double_item: ['Dois itens! Vocês vão se arrepender, porra!', 'Dobrou! Hoje eu cobro em dobro!'],
  class_select: ['{class} Mbps? Ha! Meu isopor é mais rápido!', '{class} Mbps! Rápido o bastante pra fugir da sua mãe!'],
  jump_vehicle: ['Pulei um caminhão! Toma, caralho!', 'Passei por cima do ônibus! Otário da pista!'],
  vs: {
    marco: ['Marco, seu professor de meia-tigela!', '{other}, seu aluno bagunçado, some daqui!', 'Marco, eu vou te dar nota zero, babaca!'],
    subnet: ['Subnet, cavaleiro de lata! Vai derreter na areia!', '{other}, seu feijão enlatado, sai da minha praia!', 'Subnet, tira essa armadura, porra! Está um calor!'],
    lambda: ['Sadie, sua maluca do café! Relaxa, caralho!', '{other}, para de gritar, você me dá dor de cabeça!', 'Sadie, o seu culto não paga pedágio, porra!'],
    packet: ['Pete, você é um pacote perdido! Vai pro mar!', '{other}, os cones não estão te ouvindo, doido!', 'Pete, entrega a si mesmo no penhasco!'],
    tilly: ['Tilly, sua víbora de chapéu!', '{other}, as suas pérolas são meu troféu!', 'Dona Tilly, você é uma vespa de chapéu!'],
    rex: ['Rex, sua lata de sopa com perna!', '{other}, seu robô de araque!', 'Rex, eu vou enferrujar você por dentro!'],
    biscuit: ['Biscuit, seu tapete peludo!', '{other}, seu baba-ovo de quatro patas!', 'Biscuit, faz xixi no pneu dos outros!'],
  },
};
