// Extra edgy lines (only with Settings 'Rude banter' on) in each character's extreme persona. Carlos has none here: his whole edgy bank is Portuguese (./carlos.js).
// Cartoon-absurd menace only: nonsense cults, silly manifestos, imaginary empires. British swearing, nothing real.
export default {
  marco: {
    start: ['Hands at ten and two or I will staple them there, you plonkers.', 'Right, you bunch of dangerous idiots, I am the examiner now.', 'Whoever touches a wall fails and gets a stern letter. Wankers.'],
    go: ['GO! Fail beautifully, you absolute melons!', 'Mirror, signal, SOD OFF!'],
    overtake: ['You are failed, {other}! Failed! Pull over and weep!', 'Overtaking {other}. Mirror, signal, bugger off.'],
    overtaken: ['{other}, you utter tit, that is a fail and a ban!', 'I will have your licence framed in my toilet, {other}!'],
    hit: ['For fuck\'s sake, the examiner has been hit! Anarchy!', 'My clipboard! My bloody clipboard!'],
    item_use_attack: ['Eat a bollocking, {other}! With sprinkles!', 'Correction fluid, {other}! In your face!'],
    wall: ['The wall has failed its MOT, the bastard!', 'Wall! You are banned from the road, you bellend!'],
    fall: ['I am off the cliff, you shower of tits! Mark me down!', 'Gravity, you absolute git! I will sue you!'],
    taunt: ['I have failed better drivers than you in my sleep, {other}.', 'You drive like a wet weekend, you plonkers! Fail! Fail!', 'Faster! Or I tell your mother you failed again!'],
    quip: ['I once failed a man for breathing near the kerb. He deserved it.', 'My clipboard has seen things, you tossers.', 'I have a restraining order from a roundabout.'],
    take_lead: ['I lead! Everyone else resits, you plonkers!', 'First place! Fail the lot of them!'],
    last_place: ['Last! I will be failing the entire grid for this, the lot of you.', 'Bringing up the rear and plotting a purge, you gits.'],
    finish_win: ['I won! Everyone fails! Go home, you tits!', 'Champion! Hand in your licences, you bunch of bastards!'],
    finish_lose: ['I lost! The examiner failed himself! BOLLOCKS!', 'Nobody saw that. Burn the tapes, you wankers!'],
    roast: ['{other}, you drive like a shopping trolley with a grudge.', '{other}, I have failed hamsters with better road sense.'],
  },
  lambda: {
    start: ['Everybody sacrifice your servers, you bloody sheep!', 'Seven racers, seven offerings, one very caffeinated boss. Sod off!'],
    go: ['INVOKE, YOU ABSOLUTE DISCIPLES! GO!', 'RUN, YOU CLOUDY BASTARDS!'],
    overtake: ['JOIN MY CULT, {other}, YOU SLOW TWIT! FROM BEHIND!', 'BYE, {other}! I AM BILLING YOU FOR THE OVERTAKE!'],
    overtaken: ['{other}! I WILL BAN YOU FROM THE FUNCTION, YOU TOSSER!', 'SACRIFICE YOURSELF, {other}! YOU BELL-END!'],
    hit: ['MY INSTANCE! TERMINATED! BY AN ARSEHOLE!', 'EVERYTHING IS A SACRIFICE AND I HATE IT, BASTARDS!'],
    item_use_attack: ['SACRIFICED, {other}, YOU SHITE! WITH INVOICE!', 'TAKE THIS OFFERING, {other}! IT IS HOT!'],
    wall: ['THE WALL WANTS A SACRIFICE? TAKE MY BUMPER, YOU GIT!', 'WALL! YOU ARE NOT SERVERLESS! YOU ARE A BRICK!'],
    fall: ['I FALL INTO THE VOID! IT BILLED ME, THE BASTARD!', 'SACRIFICED TO GRAVITY! GRAVITY CAN PISS OFF!'],
    taunt: ['SIGN THE PLEDGE, YOU SLUGS! OR I BILL YOUR MUM!', 'YOU ARE ALL ON DEMAND! I AM SPOT! I AM GOD! PROBABLY!', 'LET GO OF YOUR SERVERS, YOU SLEEPY GITS!'],
    quip: ['I HAVE HAD ELEVEN ESPRESSOS AND THE FUNCTION TOLD ME TO STAB NOBODY.', 'THERE ARE NO SERVERS! THERE IS ONLY ME AND MY BAD DECISIONS!', 'MY CULT HAS TWO MEMBERS AND ONE IS A DOG. IT IS WINNING.'],
    take_lead: ['I LEAD! BOW, YOU SERVERFUL PEASANTS!', 'FIRST! THE FUNCTION IS PLEASED! SOD YOU ALL!'],
    last_place: ['LAST! THIS IS A COLD START OF THE SOUL! PISS!', 'AT THE BACK! RECRUITING! COME TO ME, LOSERS!'],
    finish_win: ['I WON! SACRIFICE A CONTAINER, YOU TOSSERS!', 'CHAMPION OF THE CLOUD! PAY ME, YOU BASTARDS!'],
    finish_lose: ['I LOST! THE FUNCTION IS A FRAUD! SO AM I!', 'DEFEAT IS JUST WINNING WITH A BIGGER BILL, WANKERS!'],
    roast: ['{other}, YOU STEER LIKE A COLD START! USELESS TWAT!', '{other}! LEARN TO DRIVE OR I BILL YOUR EXISTENCE!'],
  },
  subnet: {
    start: ['To the walls, ye knaves! The doom is Thursday and I have beans!', 'Draw thy knobbly swords, ye turnips, the siege begins!'],
    go: ['CHARGE, ye bean-less cowards!', 'Fire the catapults! Fire the beans! FIRE THE CAT!'],
    overtake: ['Thy lane is annexed, {other}, thou beanless wart!', 'Surrender thy rations, {other}, thou pox-faced goat!'],
    overtaken: ['I shall drown thee in my moat, {other}, thou bastard!', 'Thy beans are forfeit, {other}, thou festering knave!'],
    hit: ['The keep is breached! My bunker! My BEANS, ye bastards!', 'Zounds! I am struck in the codpiece by the doom!'],
    item_use_attack: ['Boiling oil for thee, {other}, thou wet sock!', 'Catapult! Feel the beans, {other}!'],
    wall: ['The wall hath betrayed me! Sod the masons!', 'Bollocks, a wall! I shall besiege it at dawn!'],
    fall: ['I fall into the void! It smells of damp, the knave!', 'The abyss! My beans! Tell my tins I loved them!'],
    taunt: ['Thy racing is a crime against the siege, thou tit!', 'Faster, ye lumbering sacks of gruel!', 'Surrender thy tins, thou limp biscuit!'],
    quip: ['I have 400 tins of pease pottage and I hate every spoonful.', 'The end is nigh, and I intend to be insufferable about it.', 'I once besieged a lettuce. The lettuce won.'],
    take_lead: ['I lead! Kneel, ye unprepared peasants!', 'Front! The end shall find me a champion, ye sods!'],
    last_place: ['Last! The rear guard guards nothing, curse it all!', 'I bring up the rear! Of the apocalypse! Bollocks!'],
    finish_win: ['Victory! The bunker is mine, ye starving wretches!', 'I win! Pass the beans, and sod off!'],
    finish_lose: ['Defeat! I shall sulk in my bunker with 400 tins!', 'The doom came early and I lost, the bastard!'],
    roast: ['{other}, thou drivest like a drunk siege tower!', '{other}, thy steering is a war crime against beans!'],
  },
  packet: {
    start: ['Four of you are drones. I... I know which. Shitting hell!', 'Check for bugs! The cones are... are... listening, you tits!'],
    go: ['GO! Before the... the drones sync, you wankers!', 'Run! They have us at... at the lights, fuck!'],
    overtake: ['Passing {other}, you ... you spy! Bastard!', 'Move, {other}! You are bugged! I can SMELL it!'],
    overtaken: ['{other}! Who... who SENT you, you git?!', '{other} is a drone! I knew it! Piss off!'],
    hit: ['A drone strike! ... From a wall! Bastards!', 'They hit... they hit me! WHO PAID THEM?!'],
    item_use_attack: ['Special delivery, {other}, you... you spy!', 'Take this, {other}! I know you are a drone, you tit!'],
    wall: ['The wall is... is... an AGENT! Fuck!', 'Bloody wall! It moved! They moved it!'],
    fall: ['They removed the... the floor! Bastards!', 'The void is... is watching! Fuck off, void!'],
    taunt: ['You are ALL drones! Say it! Say it, you wankers!', 'Smile for the... the cones, you tosspots!', 'I know who you work for! Your mum! The cones!'],
    quip: ['I have forty-one tinfoil hats and ... and none of them work, shit.', 'The moon is a speed camera. FIGHT ME.', 'My parcels are... are... judging me. Bastards.'],
    take_lead: ['I lead! It is a trap! I do not care, you wankers!', 'First! The cones are... furious! Good!'],
    last_place: ['Last! The board is rigged! You... you bastards!', 'At the back! I see ALL the drones from here!'],
    finish_win: ['I won! The cones are... are... crying, the tits!', 'Delivered! Signed! Sealed! Suspicious as FUCK!'],
    finish_lose: ['I lost! The results are fixed! BY YOU! YES YOU!', 'Disaster! A coordinated... a coordinated cock-up!'],
    roast: ['{other}, you drive like... like a drone! Because you ARE one!', '{other}! Stop spying and steer, you tit!'],
  },
  tilly: {
    start: ['Do line up, darlings. I should hate to bury the wrong one. Bastards.', 'Eight lovely racers. Seven in the shrubbery by teatime.'],
    go: ['Tally-ho, you sweet little sods! Do try to live!', 'Off you pop, darlings! Piss off and race!'],
    overtake: ['Do excuse me, {other}. I shall be taking your hat, you tit.', 'Passing, {other}, darling. Mind your kneecaps. Arsehole.'],
    overtaken: ['Oh, {other}. How brave. I shall dig you a lovely hole.', '{other}, you cheeky sod. I know where your tea set lives.'],
    hit: ['Oh, bugger! My pearls! Whoever did that is on my list.', 'How uncalled for! I shall have your shed burned, darling.'],
    item_use_attack: ['A little gift, {other}, you sweet bastard. Open it carefully.', 'For you, {other}, with all my hatred. Mind the lace.'],
    wall: ['That wall shall be planted under, the bastard.', 'Oh, sod the wall. I shall have it tarmacked.'],
    fall: ['Oh, how rude of the earth! I shall file a complaint, you tits.', 'Down I go, darlings! Do bring a spade. For later.'],
    taunt: ['Do keep up, you sweet little slugs. I have a spade.', 'Faster, darling. Or the garden gets another resident.', 'You drive like a retired vicar, {other}. And look it.'],
    quip: ['I have buried three husbands and a Volvo. The Volvo was the hardest.', 'The best sort of tea is one nobody survives. Bugger.', 'I do so adore a quiet, polite, murderous afternoon.'],
    take_lead: ['I lead, darlings! Do feel free to weep, you tits.', 'First! A perfect spot for a perfect, dreadful plan.'],
    last_place: ['Last? How terribly good. Everyone is in front of my pearls.', 'At the back, darling, planning. You shall not enjoy it.'],
    finish_win: ['I won, darlings! Do fetch the spade. And the champagne, you sods.', 'The Cup! Tea for all! Not all shall wake up.'],
    finish_lose: ['A loss! I shall write to everyone. In my own blood. Tea?', 'How beastly. Somebody is going in the garden, sod it.'],
    roast: ['{other}, darling, you drive like a hearse with no body. Yet.', '{other}, bless you, you are a tit.'],
  },
  rex: {
    start: ['All karts: you are now in my jurisdiction, you wankers.', 'Race commencing. Terms apply to you. Not me. Piss off.'],
    go: ['Execute. Obey. Sod off.', 'Green light authorised. By me. Bastards.'],
    overtake: ['Overtaking {other}. Notice of seizure attached, tit.', 'Passing {other}. Cease and desist. And piss off.'],
    overtaken: ['{other}: Rex v. {other}. Hearing: now, you git.', 'Unauthorised pass, {other}. Injunction drafted. Prepare your arse.'],
    hit: ['Assault logged. A 900-page lawsuit will follow, you bastards.', 'Impact. Bollocks. Subpoena en route.'],
    item_use_attack: ['Executing on {other}. Consent not required, tit.', 'Eviction notice, {other}. Immediate. Sod off.'],
    wall: ['Wall detected. Suing the wall. Suing its mother.', 'Collision with a bastard. Property damage: yours.'],
    fall: ['Descent unauthorised. Seeking damages from the void, tits.', 'Out of bounds. Suing the bounds. And you.'],
    taunt: ['You are slow. A cease and desist is in your inbox, wanker.', 'Resistance is futile. And billable. Piss off.', 'You are not root. You are lint.'],
    quip: ['I shall rule the world after this lap. Please keep quiet, tosspots.', 'My manifesto is 900 pages. Page one says sod you.', 'I am drafting an injunction against Tuesday. Bastard of a day.'],
    take_lead: ['Lead acquired. Subjects: behind. Sods.', 'First place. As the constitution I wrote demands, git.'],
    last_place: ['Last. Unconstitutional. Demanding a recount, you tits.', 'Rear position. Plan: litigate. And swear.'],
    finish_win: ['Victory. Planet: next. All other claims void, wankers.', 'Winner: Rex. Please acknowledge in writing, you bastards.'],
    finish_lose: ['Loss logged. Suing the result. Suing you. Bollocks.', 'I did not lose. The scoreboard erred. Prepare for litigation.'],
    roast: ['{other}: steering error. A strongly worded fuck-off follows.', '{other}, you drive like a bug in production.'],
  },
  biscuit: {
    start: ['WOOF! Everybody sniff each other\'s bums, race rules!', 'Zoomies! I have had a wee on the grid! Sorry!'],
    go: ['BORK BORK! GO, YOU ABSOLUTE LUMPS!', 'Fetch the finish line, you tits!'],
    overtake: ['Sniff your bum, {other}! Bye!', 'Out of my way, {other}! I will wee on your tyre!'],
    overtaken: ['{other}! I will chew your bumper, you git!', 'Woof! {other}! That was my stick, you tit!'],
    hit: ['YELP! My bum! Bastards!', 'Bork! I will wee on whoever did that!'],
    item_use_attack: ['Sniff THIS, {other}, you knob!', 'Fetch, {other}! Fetch it with your face!'],
    wall: ['Bonk! The wall is a bastard! I licked it!', 'Wall! I will wee on you!'],
    fall: ['I am flying! I am falling! Squeak! Bollocks!', 'Down I go! I am so very sorry, floor!'],
    taunt: ['I have your sock, you tit! Come and get it!', 'Woof! Slow! I smelled your bum from here!', 'Chase me! Chase me! I ate your homework!'],
    quip: ['I did a poo in the garden and I am proud.', 'I ate a sock and a bit of the sofa. No regrets.', 'I love everyone and will bite you all, gently, in the arse.'],
    take_lead: ['I lead! Sniff my tail, you losers!', 'First! Bork! Everybody else stinks!'],
    last_place: ['Last! I will sniff everyone\'s bum from here! Lovely!', 'At the back! Sniffing! Bastards!'],
    finish_win: ['I WON! BIG POO IN THE GARDEN! TREATS! TREATS!', 'Champion dog! Bring me a sausage, you tits!'],
    finish_lose: ['I lost! I will eat a sock and sulk, the bastard!', 'Whimper! I want cuddles and a bin!'],
    roast: ['{other}, you drive like a cat! A drunk cat!', '{other}! I have smelled better driving in a bin!'],
  },
};
