// Marco, rude banter (only heard with Settings 'Rude banter' on): the weary instructor finally snaps. Sweary, self-deprecating, fourth-wall breaking.
// Six of these carry a voice key (rude_*): the catalogue lists them as optional recordings; every other line is spoken by the browser.
import { voiceLine } from '../../../core/voicelines.js';

const V = (key) => ({ t: voiceLine(key).text, key });

export default {
  welcome: ['Welcome to Marco Kart. Try not to be shite.', 'Oh, it is you. Sit down and shut up.', 'Right, class. Phones away, arses on seats.', 'Welcome back, you beautiful bastards. And you at the back.'],
  select_me: ['Marco, obviously. Who else, you muppet?', 'Bold move, picking the instructor. Let us bugger about.', 'Yes! Pick me! I am magnificent and mildly damp.'],
  gp_win: ['Cup champion! Take that, you pack of knobs!', 'I won the lot. Somebody get me a beer and a lie down.', 'Trophy for me. Detention for the rest of you.', 'Gold! Tell the students. Tell the pigeons.'],
  photo_finish: ['Photo finish! My arse just clenched to the moon.', 'That was closer than my router to the window.', 'By a whisker! A very sweaty, very sweary whisker!'],
  start: ['Right, you lot. Nobody wins but me.', 'Engines on, brains off. Let us go.', 'Eight karts, one instructor, zero dignity.', 'If anyone touches me I will fail you all.', 'It is not cheating if the teacher does it.'],
  go: ['GO GO GO, you beautiful bastards!', 'Floor it like it owes you money!', 'Off we bloody go!', 'Move, move, move! Or do not. I am going.'],
  rocket_start: ['Rocket start, you slow tossers!', 'Launched like a cannon. Bye, arseholes!', 'That was bloody perfect. Write that down.'],
  bad_start: ['Oh, for fuck\'s sake, it has stalled.', 'Bollocks, bollocks, bollocks. Stalled.', 'I am an idiot. A certified idiot, with certificates.', 'Everyone is going. I am parked. Brilliant.'],
  boost: ['WHEEE! Faster, you bloody beauty!', 'Turbo! Arse-clenching turbo!', 'Hold on to your knickers!', 'Boosting! Somebody call the police!'],
  speed: ['Flat out! My face is melting!', 'Faster than my internet. Which is bloody slow.', 'I cannot feel my face! Brilliant!', 'Flat out and absolutely shitting it.'],
  drift: ['Sideways! Like a drunk crab!', 'Drifting! Mum, look, I am cool!', 'Here goes nothing, you absolute maniac.'],
  mini_turbo: ['Kick in the arse, lovely!', 'Turbo up the tailpipe, you beauty!'],
  max_charge: ['Magenta! Full of shit and charge!', 'Maximum charge! Clench everything!'],
  overtake: [V('rude_overtake'), 'Bye-bye, {other}, you slow tosser!', 'Eat my exhaust, {other}!', 'Lovely view of your arse, {other}. Now it is behind me.', 'Sorry, {other}. Not sorry. Tough tits.', '{other}, you drive like a wet weekend in Skegness.', 'Passing {other} like a bad idea.'],
  overtaken: ['Oh, PISS OFF, {other}!', 'You complete git, {other}!', '{other}, you have earned a thunderous bollocking.', 'Overtaken by {other}. I need a lie down and a gin.', 'Get back behind me, {other}, you tit.', 'I am the teacher, {other}! Show some bloody respect!'],
  take_lead: ['First place! Kiss my arse, everybody!', 'I am in front! Bow down, you peasants!', 'Lead! I am leading! Somebody hold me!', 'Front of the pack, baby. Smell you later.'],
  lose_lead: ['Bollocks! Who took my lead?!', 'Lost the lead. I am going to cry in a cupboard.', 'Somebody nicked first place! Thieving gits!', 'Lead gone. Dignity gone. Tea cold.'],
  hit: [V('rude_hit'), 'Ow! My arse! My entire arse!', 'Bloody hell, who was that?!', 'I teach this for a living and I still got wrecked.', 'Seriously?! For fuck\'s sake!', 'That is my kneecaps in the bin.'],
  hit_by_item: ['Who threw that, you absolute bell-end?!', 'Oh, come ON! Cheating wankers!', 'I will find you. I know where you live. It is a kart.', 'Whoever did that is getting a big red fail.', 'Somebody is getting a bollocking in writing.'],
  hit_kernel_panic: ['Kernel panic? I have shat myself, more like.', 'Oh, for fuck\'s sake, a kernel panic.'],
  hit_bsod: ['Blue screen of death. Again. Piss off!', 'Stop code: Marco has had enough.'],
  hit_popups: ['Close the bloody adverts, you bastards!', 'I do not want a free iPad, you wankers!'],
  hit_shrink: ['I have shrunk! It was cold, all right?', 'Tiny! Who took my bollocks?'],
  hit_spill: ['Who spilled the flat white, you tit?', 'Slipped on a latte. Humiliating.'],
  hit_zeroday: ['A zero-day! Somebody is getting fired, probably me.', 'Booby-trapped! You sneaky bastards!'],
  hit_pigeon: ['Pigeon! Right in the gob! Bollocks!', 'Flying rat! Get it off me!'],
  item_get: ['Ooh, a present! Come to Marco!', 'Item! Time to cause some carnage.', 'Give it here, you shiny little bastard.', 'Jackpot. Somebody is about to have a terrible day.'],
  item_use_attack: ['Take that, you absolute tosser!', 'Have this, {other}, you knob!', 'Incoming, you pack of knobs!', 'Special delivery, you wankers!', 'Sod off, {other}!', 'I have got something for you, and it is not a hug.'],
  item_use_defence: ['Shields up, you bunch of bastards!', 'Try hitting me now, you muppets.', 'Protected! Kiss my shield.', 'Boost on! Hold on to your bollocks!'],
  item_hit_rival: ['Bullseye, {other}, you knob!', 'Right in the tits, {other}!', 'Got you, {other}, you slow sack of crisps!', 'Ha ha! {other} got wrecked!', 'Sorry, {other}! Wait, no, I am not.'],
  miss: ['Oh, you useless sod, that missed.', 'Missed. A waste of a perfectly good item.', 'I aim like a drunk darts team.', 'Bollocks. Missed. Try again later.'],
  dodged: ['Missed me, you wankers!', 'Ha! Nope! Not today, knob!', 'Dodged it! I am a bloody ninja!', 'Nearly had me, you sausage!'],
  block: ['Blocked! Not today, you muppet!', 'Denied! Sod off!', 'Get lost, you twats!'],
  wall: ['Ow! That is a wall. You dickhead, Marco.', 'Who moved the wall?! Bastards!', 'Right into the wall! Bloody brilliant.', 'I hit the wall. Let us not talk about it.'],
  fall: [V('rude_fall'), 'I am falling! Somebody catch me!', 'Oh, you beautiful bastard of a void.', 'Not the void again, you sod!', 'Falling! Tell the students it was DNS!'],
  respawn: ['Back in, you sods. Miss me?', 'Reconnected. Still a bit shit.', 'Dropped back down like a bad habit.'],
  offroad: ['Grass! Bloody grass everywhere!', 'Is this sand? It is in my arse!', 'Off the road! Somebody get me a map, you sods!'],
  jump: ['Wheee! Fly, you clumsy bastard!', 'Airborne! Bollocks, how do I land?', 'I am flying! Mum! Look!'],
  near_miss: ['Bloody hell! That nearly had my arse!', 'Whoa! Almost got my knackers!', 'Close one, you pack of maniacs!'],
  wrong_way: ['Wrong way! Who turned the world round?!', 'Going backwards! Somebody has pranked me!', 'Wrong way! Oh, shove it.'],
  last_place: ['Last! Even the dog is ahead!', 'Dead last. Brilliant. Absolute shite.', 'Bottom of the pile. Again. Bollocks.'],
  comeback: ['I am coming for you, you bastards!', 'Watch me climb, you smug tossers!', 'Comeback time! Keep your knickers on!'],
  lap2: ['Lap two. My arse is sweating.', 'Lap two, and I am already knackered.'],
  final_lap: ['Final lap! Do not you dare overtake me, you knobs!', 'Last lap! Let us cause some chaos!', 'Final lap! Shit or bust!'],
  finish_win: [V('rude_win'), 'First! Eat my dust, losers!', 'I won! Tell the students! Tell the pigeons!', 'Winner! Bow down, you unwashed plebs!'],
  finish_podium: ['A podium! Somebody give me a drink!', 'Not first, but I will take it, you sods.', 'Podium! Get in! Not gold, but bloody close.'],
  finish_lose: [V('rude_lose'), 'I will be in the bath. Crying.', 'I will be in the cupboard with the spare routers.', 'I hate this. I hate all of you. Especially Tilly.'],
  taunt: [V('rude_taunt'), 'Come on, slowcoaches, I am bored!', 'I have seen snails go faster! Snails in flip-flops!', 'Keep up, you tossers!', 'Wakey wakey, dickheads!'],
  quip: ['Is this a simulation? I want to speak to the manager.', 'I taught the OSI model to two hundred people. It did not help.', 'If I win this, I am buying a ridiculous hat.', 'Somebody is scripting all this. Show yourself!', 'Eight certificates and no bloody idea how to brake.', 'Somewhere a student is screaming at a subnet. Good.', 'Is that applause? Who is clapping? Turn it off.', 'I can hear the producers laughing at me.', 'Cut to me looking devastated. And scene.', 'This kart has more horsepower than my career.', 'Why is there a dog in the race? Why am I losing to it?', 'Somebody get this man a biscuit and a lie down.'],
  roast: ['Drive properly, {other}, you absolute melt.', 'You drive like my nan, {other}, and she is a coat stand.', 'Learn to drive, {other}, you turnip.', '{other}, I have seen better steering on a shopping trolley.', 'Mind the wall, {other}. Oh, too late, you tit.'],
  bump: ['Oops! Did I hit you, {other}? Good.', 'Move your kart, {other}, you knob.', 'Budge up, {other}, you lump!'],
  bumped: ['Oi! Watch it, {other}, you absolute melon!', 'Get your bumper off my arse, {other}!', 'Do that again and I will bite your tyre, {other}!'],
  perfect_jump: ['Perfect take-off, you beauty!', 'Stuck the take-off, you smug sod!'],
  swap_item: ['Swapsies, you greedy sod!', 'Switcheroo, you bloody magpie!'],
  double_item: ['Two items! Somebody is going to cry!', 'Double trouble, you bastards!'],
  class_select: ['{class} Mbps? My nan\'s Wi-Fi is faster.', '{class} Mbps. Right, this should be a laugh.', 'Fast enough to shit myself. Lovely.'],
  jump_vehicle: ['Launched off a lorry! Bollocks to gravity!', 'Jumped a bus. Take that, physics!'],
  vs: {
    lambda: ['Sadie, slow down, you caffeinated hamster!', '{other}, I have met smoke alarms calmer than you.', 'Sadie, you are on spot pricing and I am on my last nerve.'],
    subnet: ['Sir Subnet, you look like a tin of beans with ambition.', '{other}, put your visor down, you tit.', 'Sir Subnet, get your lance out of my road!'],
    packet: ['Pete, you are about as reliable as public Wi-Fi.', '{other}, you useless lost parcel.', 'Pete, I am not signing for that, you twit.'],
    carlos: ['Carlos, stop sipping and start driving, you beach bum.', '{other}, you have got limes where your brain should be.', 'Carlos, wake up, you horizontal sod!'],
    tilly: ['Tilly, your flask is full of gin, is it not?', '{other}, you pearl-clutching menace!', 'Tilly, you sweet little hooligan. Move!'],
    rex: ['Rex, you overgrown toaster.', '{other}: sudo shut up.', 'Rex, I have had milk with more personality.'],
    biscuit: ['Biscuit, stop sniffing bins and drive!', '{other}, you furry little git!', 'Biscuit, that is my tyre, you maniac!'],
  },
};
