// Packet Pete, rude banter: the lossy courier. Stuttery, glitching, dropping words mid-insult ("..." = packet loss), sure every delivery is someone else's fault.
export default {
  welcome: ['Wel-wel-welcome, you... bunch of... sods!', 'Delivery for ... you, you tits! Sign here!', 'Connected! Connec... bollocks, dropped again!'],
  select_me: ['Pick me! I am... I am... lossy but lovely, you knobs!', 'Me? Fuh-fuh-fucking right!', 'Excellent choice! I am... ACK! Ack! Piss off!'],
  gp_win: ['I w-w-won the Cup! Delivered! Sign for it, tossers!', 'Cup de-de-delivered! To ME, you bastards!', 'Champion! Out of ord-ord-order but CHAMPION!'],
  photo_finish: ['That was... that was... ...packet-loss close, you sods!', 'Photo finish! I nearly s-s-shat a parcel!'],
  start: ['Preparing to... to... transmit, you tossers!', 'Packet Pete, ... ready to deliver a kicking!', 'Get out of my... my... lane, you lot!', 'Sending! ...sending! Damn it! Sending!'],
  go: ['GO-GO-GO, you beautiful... b-bastards!', 'Transmitting! ...transmi... bollocks!', 'Send it, you... wankers!', 'SYN! SYN! SYN, you knob-ends!'],
  rocket_start: ['Zero la-la-latency, you slow tits!', 'First packet out! Eat my... my... ping!', 'Fast! Fast! F-f-fast as shit!'],
  bad_start: ['Time-time-timeout! Bloody timeout!', 'Stalled! Stall-stall-stalled! Bastard!', 'Packet d-dropped at the start. Wanker!'],
  boost: ['Bandw-bandwidth! Biggie! Whee!', 'Jumbo f-frame, you tits!', 'Boost! ...boost! Clear the... road, knobs!', 'Faster than... than... your mum\'s Wi-Fi!'],
  speed: ['Zero packet loss! ... OK, four percent!', 'Full throughput! Full f-fucking throughput!', 'Flat out and... absolutely... shitting myself!'],
  drift: ['Sideways! ... Out of... order! Whee!', 'D-d-drifting like a dropped frame!', 'Slide! Slide! ...slide, you bastard!'],
  mini_turbo: ['Burst! Burst! Packet burst, you tits!', 'Mini-mini-mini turbo, you sod!'],
  max_charge: ['Maximum ... jitter! Brace!', 'Full load! Full... fuck... load!'],
  overtake: ['P-passing you, {other}, you limp... sod!', 'Out of your way, {other}! ... I am routing round you!', 'Bye-bye, {other}! Delivered past you, you tit!', 'Reorder THIS, {other}!', '{other}! Move your... your... arse!', 'TTL expired, {other}! Piss off!'],
  overtaken: ['Y-y-you... you wanker, {other}!', '{other}! That was MY hop!', 'Overtaken? By {other}? Bastard! Bastard! Bastard!', 'Nice p-p-packet, {other}, shame about your face!', '{other}, you routing tit!'],
  take_lead: ['F-f-first! First out! First... in!', 'I lead! I led! Delivered! Lead! Bollocks!', 'Front of the queue, you tossers!'],
  lose_lead: ['My lead! ...dropped! Bollocks!', 'Who... who stole the lead?! I want a refund!', 'Lead lost in... transit! Bastards!'],
  hit: ['OW! ... My... my payload! Bollocks!', 'Packet l-l-lost! Ow! Git!', 'I have been... undelivered! By a tit!', 'Ack! ... Nack! ...Fuck!', 'Crash! Crash! Dammit! Crash!'],
  hit_by_item: ['Who... who sent that?! I demand a... receipt!', 'That was a... malicious packet, you wankers!', 'I will trace... trace you! Bastards!', 'Return to sender, you tossers!'],
  hit_kernel_panic: ['Kernel p-p-panic! I have... soiled... the stack!', 'The kernel... the kernel... has shat itself!'],
  hit_bsod: ['Blue ... blue ... bollocks!', 'BSOD! Packet... ded!'],
  hit_popups: ['Pop-ups! Pop... pop... off!', 'Close it, you bloody... ad-ad-advertisers!'],
  hit_shrink: ['Compressed! ...lossy! Bastards!', 'I am... a tiny... packet! Sod this!'],
  hit_spill: ['Spill! My... my parcel is soggy!', 'Soggy parcel! Who d-did this?!'],
  hit_zeroday: ['Zero-day! My... ports! Open! Shit!', 'Exploit! My firewall is a... sieve!'],
  hit_pigeon: ['Pigeon! Carrier... carrier pigeon! Rival!', 'Bird! I am the courier! It is the... competition!'],
  item_get: ['Item! Sign for it... you tits!', 'Package! For... me! Somebody\'s going down!', 'Delivery! And it is... a bastard!', 'Got a thing! Oh, this is going to hurt!'],
  item_use_attack: ['Special delivery, {other}, you tit!', 'Have a... a... package, {other}!', 'Return to s-s-sender, {other}, you sod!', 'Sending you... something horrible!', 'Payload ... incoming, you wankers!'],
  item_use_defence: ['Firewall ... up! Try me, you knobs!', 'Encrypted! Bugger off!', 'Packet-filtering your arse!'],
  item_hit_rival: ['Delivered to {other}! Sign here, tit!', 'Direct hit, {other}! ... Ack!', 'Got you, {other}! ... ... got you!', 'Bullseye! {other} is now... lost in the post!'],
  miss: ['Missed! ... Returned to sender!', 'Packet lost! Bloody lost!', 'Dropped! ... Dropped my shot, you... ugh!'],
  dodged: ['Nope! ... dropped! Ha!', 'Ha! ... You missed, you twits!', 'Null route! Null route! Ha!'],
  block: ['Blocked! ... Firewalled, you sod!', 'Denied! ... dropped! Pah!', 'Not today, you... you... bastard!'],
  wall: ['Wall! Wall! Who... wall?! Bastard!', 'Ow! Wall! Stupid, stupid wall!', 'Crashed. Again. Bollocks. Again.'],
  fall: ['Fall... falling! ... lost connection! Bastards!', 'Oh ... oh shit ... void!', 'Down ... d-d-down ... dropped!'],
  respawn: ['Re... re... resent! Take that!', 'Back online, you... you sods!', 'Retransmit... retransmit... retransmitted!'],
  offroad: ['Grass! Got... grass in... my exhaust!', 'Off-road! Undelivered! Shit!', 'Wrong... wrong route! Sod it!'],
  jump: ['Flying! ...flying! ...fl-fl-flying!', 'Airmail! Airmail! Bollocks!', 'Up! Up! And... down... badly!'],
  near_miss: ['Near... near packet collision!', 'Phew! I almost... dropped my arse!', 'That was... 0.2 mm of delivery!'],
  wrong_way: ['Wrong... wrong way! Route reversed! Shit!', 'Backwards! I am... shipping myself backwards!', 'Return to... sender! ME! I am the sender!'],
  last_place: ['Last! Last in the... queue! Bastards!', 'Undelivered... and last... and furious!', 'Dead last! ... ...Shit shit shit!'],
  comeback: ['Coming for you! Delivery... incoming!', 'Catching ... catching ... catching you, tits!', 'Re-routing through your... faces!'],
  lap2: ['Lap two! Halfway to... hell!', 'Second lap! Second... helping of shite!'],
  final_lap: ['Last lap! Everything... must go! Must! Go!', 'Final lap! Deliver... deliver... deliver!', 'Last lap! Deliver or die... trying!'],
  finish_win: ['Delivered! First! ... Sign for it, you losers!', 'I won! Mail... me the trophy! Right now!', 'First! Out of... order and out of... your league!'],
  finish_podium: ['Podium! Gold... ish! Nearly! Bastards!', 'Top three! Delivered... to the podium!', 'Not bad... for a... a parcel!'],
  finish_lose: ['Lost in the... post! Bollocks!', 'Undeliverable! ... Again! Sodding hell!', 'Returned to... sender! I hate this!'],
  taunt: ['Slow! So... slow! Dial-up, you tossers!', 'Faster! ...faster! ...you sacks of crisps!', 'You are... delayed, you slugs!', 'Buffering! ... ha! You are buffering!', 'Your ping is... shite! Shit shit shit!'],
  quip: ['I sent a l-letter. It is still in my... my... belly!', 'Do you ever feel... like a... like a... parcel?', 'I lose ... 12 percent of everything! Especially patience!', 'Somebody is... is... watching this! Hello! Wankers!', 'Is that a ... dog in a hat? No? Bollocks!', 'Out of... out of... order, me! Not him!', 'I am a good boy! ... Not a good boy! ... A pest!', 'Why ... is ... everything ... so ... far?!', 'I dropped ... my lunch ... somewhere ... back ... there.'],
  roast: ['{other}! You drive like a... like a dropped call!', '{other}, your steering is... shite!', 'Learn to... to... drive, {other}, you tit!', '{other}, you have more lag than a... hippo!', 'Oi, {other}! Brake! ... Not that one! The other one!'],
  bump: ['Bump! Sorry, {other}! ... Not sorry!', 'Oops! ...{other} is in my way!', 'Budge! Budge! Budge, {other}!'],
  bumped: ['Ow! ... {other}! You absolute... tit!', 'Get off my... bumper, {other}!', '{other}! You dropped me! Bastard!'],
  perfect_jump: ['Perfect take-off! Sent! ...Received!', 'Stuck it! Lucky! ... Skilful!'],
  swap_item: ['Swap! ... Swapped! You... sucker!', 'Switch! Switch! You... twits!'],
  double_item: ['Two... items! Double... delivery!', 'Double! Double! ... Double bollocks!'],
  class_select: ['{class} Mbps? ... My line is... garbage!', '{class} Mbps! Fast... enough for... me!', 'That is {class} Mbps of... shite!'],
  jump_vehicle: ['Jumped a... lorry! Airmail!', 'Over the bus! ...Take that, traffic!'],
  vs: {
    marco: ['Marco! You... teach, I... deliver kicks!', '{other}! Your... lessons are... lossy!', 'Marco! Pop... quiz: where is your... lunch?'],
    subnet: ['Sir Subnet! ... You clank like a... shopping trolley!', '{other}, get... your visor... out of my... way!', 'Subnet! Out of... order! Out of... your depth!'],
    lambda: ['Sadie! Stop... shouting! It is... in my... header!', '{other}! You are... so loud! I dropped a packet!', 'Sadie! Your... invoice! Is shite!'],
    carlos: ['Carlos! Wake... wake up, you... slow sod!', '{other}! You are... asleep! And... on fire!', 'Carlos! Drive! Not... drink!'],
    tilly: ['Tilly! ... Your tea is... a... war crime!', '{other}! You... posh... menace!', 'Tilly! Pearls! Off! Now!'],
    rex: ['Rex! ... Your... sudo is... shit!', '{other}! Robot! Piss... off!', 'Rex! Your... permissions... denied!'],
    biscuit: ['Biscuit! ... Do not... eat... my parcel!', '{other}! You... dog! ... Bad dog!', 'Biscuit! ... Sit! Sit! ... Sod off!'],
  },
};
