// Root Rex, rude banter: the deadpan robot with sudo on the whole circuit, swearing in shell commands and error codes. Flat delivery, unhinged content.
export default {
  welcome: ['root@marco-kart:~# hello, you absolute wankers', 'Access granted. Sit down, you muppets.', 'Login: rex. Password: fuck off.'],
  select_me: ['sudo select rex. Confirmed. Obey.', 'Good choice. Permission granted. Shut up now.', 'Privileges escalated. You are welcome, you tit.'],
  gp_win: ['sudo win --cup. Executed. Weep.', 'Cup acquired. All your base are belong to my arse.', 'Victory logged. Your tears are in /var/log/losers.'],
  photo_finish: ['Margin: 0.02 seconds. My circuits clenched.', 'Photo finish. Checksum matches. Bowels do not.'],
  start: ['Initialising race. Nobody is root but me.', 'All processes, prepare to be killed.', 'rm -rf /opposition. Executing.', 'Grid formation: acceptable. You lot: not.'],
  go: ['sudo go. NOW, you bellends.', 'Execute! Bastards!', 'exec race. Piss off.', 'Running! Nobody stop me, you wankers.'],
  rocket_start: ['Zero latency launch. Weep, scripts.', 'Optimal. As expected. Eat my stack trace.', 'Startup: nominal. You are all shite.'],
  bad_start: ['Segmentation fault. At the start. Fuck.', 'Timeout. Retry. Bollocks.', 'Error 500: slow start. Somebody is getting fired.', 'Process hung. I hung it. Sorry.'],
  boost: ['Overclock engaged. Smell the burning.', 'Boost: 100 percent. My balls are warm.', 'Throughput increased. Stand clear.', 'sudo boost. Do not ask permission.'],
  speed: ['Maximum throughput. Zero errors. Zero mercy.', 'Speed: obscene.', 'Straight line. Efficient. Smug.'],
  drift: ['Executing slide. Lateral movement initiated.', 'Drifting. Within tolerance. Barely. Shit.', 'Sideways: allowed. Crying: denied.'],
  mini_turbo: ['Burst released. Tiny, filthy burst.', 'Minor overclock. Major arse.'],
  max_charge: ['Maximum charge. Priority: root. Priority: mayhem.', 'Charged. Fire. Fire! Fire at will, you tit.'],
  overtake: ['Passing {other}. Nobody asked. Piss off.', 'Bypassing {other}. Waste of electricity.', '{other}: overtaken. Kernel: smug.', 'Rerouting around {other}. Dead weight.', 'Access granted, {other}. Goodbye, you slow git.', 'Moving {other} to the past. The past is shite.'],
  overtaken: ['{other}: access denied. Bollocks.', 'Unauthorised overtake, {other}. I will end you.', 'Logging incident. {other} is a wanker.', 'Overtaken by {other}. Revoking your birthday.', 'Permission denied, {other}, you tit.'],
  take_lead: ['I have root on first place. Kneel.', 'First place: acquired. Weep.', 'Leader process: rex. All others: garbage.', 'Positions sorted. I am first. You are bollocks.'],
  lose_lead: ['Lead lost. Investigating. Someone will die. Probably.', 'Position: overwritten. By a git.', 'Reinstating lead. Eventually. After I smash someone.'],
  hit: ['Error. Fuck.', 'Permission denied! Bastards!', 'Impact detected. My circuits hurt.', 'Hardware fault. Somebody pays.', 'Ow. Logged. You are next.'],
  hit_by_item: ['Unauthorised item usage. I will find your IP, tosser.', 'Attack logged. Revenge scheduled. Arsehole.', 'Intrusion detected. Kill signal queued.', 'Somebody is going on the naughty list, twat.'],
  hit_kernel_panic: ['Kernel panic. My kernel is shitting itself.', 'Panic. Core dumped. Bollocks dumped.'],
  hit_bsod: ['Blue screen. Fatal error: dignity.', 'STOP: rex. Fuck off, Windows.'],
  hit_popups: ['Ad-blocker: offline. Adverts: bastards.', 'Closing all tabs. All of them. Forever.'],
  hit_shrink: ['Compressed. I am 50 percent less robot.', 'Downsized. Laid off. Bollocks.'],
  hit_spill: ['Liquid on hardware! Who is the wanker?', 'Spillage. Short circuit. Sod it.'],
  hit_zeroday: ['Zero-day! Someone is getting fired.', 'Exploit executed against me. Motherboard: furious.'],
  hit_pigeon: ['Pigeon. Unidentified process. Terminate pigeon.', 'Feathers in the exhaust. War declared.'],
  item_get: ['Item acquired. Someone is getting deleted.', 'Download complete. Targeting: everyone.', 'New file. Accepting. Weaponising.', 'Loaded. Good. Bastards.'],
  item_use_attack: ['sudo attack {other}. No permission needed.', 'Executing on {other}. Sorry. No.', 'Firing. {other} is a wanker.', 'Target locked: {other}. Goodbye.', 'Payload: delivered. To your face, {other}.'],
  item_use_defence: ['Defences online. Try me, tits.', 'Root shield: active. Bugger off.', 'Privileges locked down. Die mad.'],
  item_hit_rival: ['{other}: terminated. Your mother is a deprecated library.', 'Direct hit, {other}. Rebooting your face.', 'Kill signal sent to {other}. Process: dead.', '{other}: deleted. Lovely.'],
  miss: ['Target missed. I will kill something else.', 'Error: aim. Segfault: me.', 'Null pointer. It went nowhere. Bastards.'],
  dodged: ['Attack failed. Ha. Wankers.', 'Evaded. You are incompetent.', 'Threat avoided. You are still a tit.'],
  block: ['Access denied. Fuck off.', 'Attack blocked. Predictable, you muppets.', 'Permission: not granted. Ever.'],
  wall: ['Collision detected. Wall: hostile. Also shite.', 'Impact logged. Wall will be deleted.', 'Hardware: dented. By a wall. Bollocks.'],
  fall: ['Error: ground not found. Bollocks.', 'Falling. Stack trace: down.', 'Void detected. Void: bastard.', 'Off the map. Awkward. Fuck.'],
  respawn: ['Rebooting. Try me again, you sods.', 'System restored. Hate restored.', 'Restarted. Delete them all.'],
  offroad: ['Off-road detected. Sand is in my bolts.', 'Grass: unwanted. Delete grass.', 'Terrain: not tarmac. I am furious.'],
  jump: ['Airborne. Gravity: negotiable.', 'Ballistic. Shit.', 'Flight mode. Landing gear: missing.'],
  near_miss: ['Near collision. Ignored. Soiled.', 'Damage: nil. Dignity: bruised.', 'Close call logged. Phew. Sod.'],
  wrong_way: ['Direction: wrong. World: wrong. I am right.', 'Heading reversed. Shit.', 'Backwards. Not intended. Fix: hit something.'],
  last_place: ['Position: last. Temporary. Somebody will pay.', 'Rank: eight. Correcting. Angrily.', 'Trailing. Intentionally. Probably.'],
  comeback: ['Recovering positions. Deleting rivals.', 'Comeback: initiated. Bring flowers.', 'Catching up. Processing. Smashing.'],
  lap2: ['Lap two. Nominal. Fuck.', 'Second iteration. Still furious.'],
  final_lap: ['Final loop. Delete everyone.', 'Last iteration. Terminate rivals. Terminate rivals.', 'Final lap. Executing. And you.'],
  finish_win: ['Race won. sudo win. Weep.', 'First. Exit status: zero. Zero fucks.', 'Victory logged. Polish my chassis.'],
  finish_podium: ['Podium acquired. Not first. Noted. Grudge.', 'Top three. Acceptable. Not really.', 'Trophy: received. I want more.'],
  finish_lose: ['Exit status: one. Fuck.', 'Defeat logged. Somebody is going to get deleted.', 'Not first. Investigating. Hostile.'],
  taunt: ['Permission denied. Again. Loser.', 'You are not root. You are not anything.', 'Ping. Timeout. Absolute loser.', 'Slow process detected. Killing your process.', 'Your speed is illegal. Your face is worse.'],
  quip: ['rm -rf slowness. rm -rf you.', 'sudo make me a sandwich and sod off.', 'There is no place like 127.0.0.1. And I am still lost.', 'I am not a robot. Actually, I am. Shit.', 'Feelings: null. Rage: 100 percent.', 'Error 418: I am a teapot and I am furious.', 'Why is there a dog in the race? I have no answer.', 'kill -9 the applause. Now.', 'Is this a simulation? I will sudo the simulator.', 'Somebody is watching my packets. Stop it.'],
  roast: ['{other}: your driving is a segmentation fault.', 'Your steering, {other}, is deprecated.', '{other}, you handle like a corrupted file.', 'Error: {other} cannot drive. Replace driver.', 'Your mother is a deprecated library, {other}.'],
  bump: ['Collision: {other}. Not sorry.', 'Shoving {other} aside. As root.', 'Bumped {other}. Deliberately. Piss off.'],
  bumped: ['{other}, keep your distance, you tit.', 'Unauthorised contact. {other} will be deleted.', 'Do not touch the chassis, {other}.'],
  perfect_jump: ['Optimal take-off. Fuck yes.', 'Perfect. Logged. Smug.'],
  swap_item: ['Swapped. Stole. Enjoy.', 'Switched. Do not ask.'],
  double_item: ['Two items. Two crimes.', 'Double payload. Delightful.'],
  class_select: ['{class} Mbps. Slow. I will overclock it.', '{class} Mbps. Enough to ruin you.', 'Bandwidth: {class} Mbps. Dickhead-tolerance: zero.'],
  jump_vehicle: ['Lorry jumped. Sudo jump.', 'Over the bus. Obviously.'],
  vs: {
    marco: ['Marco, your permissions are insufficient, you tit.', '{other}: not your class. Not your anything.', 'Teacher. You are not root. You are a pillock.'],
    subnet: ['Sir Subnet: /24 is tiny. So are you.', 'Knight. Your armour has no root. Wanker.', '{other}: remove your helmet. And your head.'],
    lambda: ['Sadie: lower your voice. Or I lower it.', '{other}: you are a cron job with attitude.', 'Sadie, you are a fire alarm in a hoodie.'],
    packet: ['Packet. Dropped. Deservedly.', 'Pete, you are a bug in a parcel.', '{other}: timeout. Forever.'],
    carlos: ['Carlos, you are a lime with legs. Delete.', '{other}: wake up. Or I wake you.', 'Carlos, your uptime is zero. Your downtime is infinite.'],
    tilly: ['Tilly: your tea is a Class A error.', '{other}: sudo shut up.', 'Tilly, you are a biological sudo. Sod off.'],
    biscuit: ['Biscuit: bark. Bark. Segfault.', '{other}: dog detected. Good boy. Error: cute overflow.', 'Biscuit: stop peeing on my bumper.'],
  },
};
