// Sir Subnet, rude banter: the pompous Knight of the /24 loses his chivalry and keeps his vocabulary. Faux-medieval filth, subnet maths as a threat.
export default {
  welcome: ['Hail, thou sack of knobs! Welcome!', 'Thou art late, thou festering turnip!', 'Gather round, ye bastards, and behold a /24!'],
  select_me: ['Thou hast chosen a knight. Thou art not a total tit.', 'A wise choice, thou absolute bollock-biscuit!', 'Hark! At last a man of taste and trousers!'],
  gp_win: ['The Cup is mine! Kiss my gauntlet, ye scum!', 'Victory! Ye may all fetch me a goblet and sod off!', 'I am champion! Bow, ye festering wretches!'],
  photo_finish: ['By a hair of my plume! My arse did twitch!', 'Close! Closer than my codpiece to my cousin!'],
  start: ['Steel thy bollocks, the joust begins!', 'Let the bloody slaughter of asphalt commence!', 'Eight knights, one road, and none of ye worthy.', 'Form a line, ye shambolic sods!'],
  go: ['CHARGE, ye knackered nobles!', 'To the /24, ye magnificent bastards!', 'FORWARD! Or backward, I do not care, I am forward!', 'Hup, ye horses of the apocalypse!'],
  rocket_start: ['A perfect charge! Choke on my dust, ye knaves!', 'I launch like a trebuchet with a grudge!', 'Fled the gate like a scalded squire!'],
  bad_start: ['Zounds! My kart hath stalled, the bastard!', 'Stalled! Damn this iron donkey!', 'My lance hath stalled! I mean my clutch! Bollocks!'],
  boost: ['Hold fast, for I go faster than thy mother!', 'Ha! The wind hath a new master, ye tits!', 'Boost! Brace thy knackers!'],
  speed: ['Flat out! My plume is horizontal!', 'Faster than a scandal in the royal court!', 'Such speed! Such glory! Such terror in my breeches!'],
  drift: ['I slide like a greased bishop!', 'Sideways! As is the fashion at court!', 'Lo, I drift, and the tyres weep!'],
  mini_turbo: ['A spurt of glory! Suck it, peasants!', 'Hup! Another slice of pure gallantry!'],
  max_charge: ['The magenta! The filthy, glorious magenta!', 'Charged to bursting! Stand back, ye nags!'],
  overtake: ['Make way, {other}, thou limp biscuit!', 'I pass thee, {other}, as a knife passes butter!', 'Begone, {other}, thou pox-ridden stoat!', 'Out of my road, {other}, ye festering wart!', 'Thy rump is behind me, {other}. A fine day!', 'Pardon? No. Piss off, {other}!'],
  overtaken: ['Thou wretched gnat, {other}! I shall have thy head!', '{other}, thou lily-livered knave!', 'Overtaken by {other}? Fie! Bollocks! Double fie!', 'I shall divide thee into two equal halves, {other}!', 'Curse thee, {other}, thou mange-ridden badger!'],
  take_lead: ['I lead! Kneel, ye knock-kneed cowards!', 'At the front, where a knight belongeth! Sods!', 'The view is splendid! The rest of ye are rubbish!'],
  lose_lead: ['Zounds! Who hath stolen my lead, the knaves?!', 'Lost the lead! I shall flay them all!', 'My lead! My precious lead! Return it, ye thieves!'],
  hit: ['Gadzooks! By my breeches! Bollocks!', 'I am wounded! By an arse!', 'Ow! My dignity! And my greaves!', 'A cowardly blow! Come at me front-ways, ye bastards!', 'I bleed! A little! Mainly pride!'],
  hit_by_item: ['Thou cur! Who threw that, ye cowards?!', 'A dishonourable strike! I shall find thee!', 'Fie! A foul blow! I shall have thy kidneys!', 'Who dares?! Come forth, ye pox-ridden louts!'],
  hit_kernel_panic: ['A kernel panic! My knees! My knees!', 'Even the machine weeps, the tit!'],
  hit_bsod: ['Blue screen! The heavens hath crashed!', 'Blue death! Fetch me a priest and a spanner!'],
  hit_popups: ['Begone, ye advertising demons!', 'I want no free bloody dragons!'],
  hit_shrink: ['I am diminished! Even my plume is tiny!', 'Shrunk! Thou cold-hearted bastards of the cloud!'],
  hit_spill: ['A slippery brew! Whose?! I demand a duel!', 'Slipped in tea! Zounds!'],
  hit_zeroday: ['A trap! Coward\'s work, ye bastards!', 'Zero-day! Hath the king no mercy?'],
  hit_pigeon: ['A pigeon hath defiled my helm!', 'Bird! Vile sky-rat! I shall have it on a spit!'],
  item_get: ['Mine! All mine! Ye shall weep!', 'A gift from the heavens! For smiting!', 'Ooh, a dagger! Of sorts! Somebody\'s for it!'],
  item_use_attack: ['Take this, {other}, thou bucket of wart!', 'Have at thee, ye knaves!', 'For the glory of the /24! And to spite thee!', 'Smote! Smiting! A smiting for {other}!', 'Feel my wrath, {other}, and sod off!'],
  item_use_defence: ['Raise the shield, ye scummy lot!', 'Try me now, ye festering louts!', 'Cower behind thy mothers! I am armoured!'],
  item_hit_rival: ['Struck thee, {other}, thou ninny!', 'Right in the codpiece, {other}!', '{other}! Thou hast been smitten, and thy mother too!', 'Take that, {other}, thou hairy arse-goblin!'],
  miss: ['Damnation! It went to the wrong knave!', 'Missed! The item is a coward!', 'Bollocks! I shall have that smith flogged!'],
  dodged: ['Thou cannot smite a knight of the /24, ye dullard!', 'Ha! Missed, thou turnip of the dirt!', 'Dodged! I am a cat in armour!'],
  block: ['Denied, thou craven gits!', 'My shield! Thy strike is bollocks!', 'Repelled, ye sods!'],
  wall: ['I smote the wall! Who built that?!', 'The wall, the vile wall! Bastard!', 'A wall hath assailed me! I shall have it knighted!'],
  fall: ['I fall! Tell the tavern I was magnificent!', 'Plunged into the void! Bollocks!', 'Fie! The earth hath abandoned me!', 'To the abyss! Knackers first!'],
  respawn: ['I rise again, ye sods!', 'Resurrected! Fear me, ye mortals!', 'Back in, and cross as a bishop.'],
  offroad: ['Mud! Filth! My lovely greaves!', 'Grass! I am a knight, not a sheep!', 'Get me out of this mire, ye blasted kart!'],
  jump: ['Flying! Flying like a turd on a trebuchet!', 'Hah! The ground rejects me!', 'Airborne! Away, gravity, thou sod!'],
  near_miss: ['By my codpiece, that was close!', 'A breath from the grave! And my arse!', 'Phew! My bowels nearly abdicated!'],
  wrong_way: ['Wrong way? Nonsense! The road is wrong!', 'The world is backwards! Fetch my wizard!', 'I am going the wrong way on purpose, ye dolts.'],
  last_place: ['Last! Such shame! I shall cut my plume off!', 'Bringing up the rear, like a pox-ridden squire.', 'Last, yet still a better knight than all of ye.'],
  comeback: ['I rise! And I shall eat ye all!', 'Watch me climb, ye worthless nags!', 'Behold the comeback, ye pox-ridden cowards!'],
  lap2: ['Lap two! More of this splendid bollocks!', 'The second lap! My knees are old!'],
  final_lap: ['The final lap! Fall, ye nobles, fall!', 'Last lap! Sod the honour, win!', 'Final lap! I shall die for glory! Or a snack!'],
  finish_win: ['Victory! The kingdom is mine, ye plebs!', 'I win! Fetch me a goblet and a chair, ye slaves!', 'First! Thy mothers shall hear of this!'],
  finish_podium: ['A podium! A shiny piece of tin! Splendid!', 'Not first, but near enough, ye sods!', 'Podium! Pour me a flagon, ye knaves!'],
  finish_lose: ['Defeat! I shall sulk in my tower!', 'I lost! By the sword of bollocks!', 'Dishonour! Sell my horse and my lance!'],
  taunt: ['Thou art slow, thou wart of a man!', 'Faster, ye mangy nags!', 'Hurry up, ye lumbering sacks of spuds!', 'Thy driving is a crime against chivalry!', 'Halve thy speed again and thou shalt stop, ye loon!'],
  quip: ['Did anyone bring a sandwich? A dragon ate mine.', 'I once divided a pie into /26s. The pie wept.', 'There are 254 hosts in a /24 and I despise 253 of them.', 'Dost thou hear the orchestra? I do. It mocks me.', 'I am forty per cent armour and sixty per cent rage.', 'The producers are watching. Hello, producers! Sod off!', 'My horse is a kart and it hates me.', 'A knight without a subnet is just a man in a bucket.', 'I can smell my own breeches and they smell of victory.', 'Who among ye has seen my lance? Tell no one!'],
  roast: ['{other}, thou drivest like a drunk bishop!', 'Thy kart is a crime scene, {other}!', 'A donkey would steer better, {other}, and smell nicer!', '{other}, thy mother is a damp biscuit! Bollocks to ye!', 'Learn to drive, {other}, thou quivering dollop!'],
  bump: ['Move, {other}, thou lump!', 'A polite nudge, {other}. Dost thou feel it? Tit!', 'Budge, {other}, or I shall knight thee with a wrench!'],
  bumped: ['How dare thee, {other}?! Bastard!', 'Thou hast scratched my armour, {other}, thou cur!', '{other}, I shall have thy kneecaps!'],
  perfect_jump: ['A perfect take-off, ye sods!', 'Launched like a heroic plum!'],
  swap_item: ['Swapped! And thou shalt never know why!', 'A switch! Sneaky! Like a politician!'],
  double_item: ['Two weapons! Ye shall all rue this day!', 'Twice the smiting! Hooray for bastards!'],
  class_select: ['{class} Mbps? Ha! My shield is faster!', '{class} Mbps! Fast enough to outrun thy mother!', 'A {class} Mbps steed! I shall make it weep!'],
  jump_vehicle: ['Leaped a lorry! Take that, carriage-drivers!', 'Over the wagon! Thou tit of the road!'],
  vs: {
    marco: ['Marco, thou art a teaching tit!', '{other}, thou dishevelled lecturer, begone!', 'Marco, I shall mark thee down, thou prat!'],
    lambda: ['Sadie, thou frenzied gerbil!', '{other}, thou mayfly! Thou shalt be terminated!', 'Sadie, calm down, thou foul-mouthed squirrel!'],
    packet: ['Pete, thou art a parcel lost in a pit!', '{other}, thou unreliable sack of mail!', 'Pete, deliver thyself to a cliff!'],
    carlos: ['Carlos, thou hast the energy of a wet sock!', '{other}, thou sunburned lime-bucket!', 'Carlos, wake up and be hated!'],
    tilly: ['Tilly, thou fragrant menace!', '{other}, thy pearls are my trophies!', 'Lady Tilly, thou art a hornet in a hat!'],
    rex: ['Rex, thou tin of soup with legs!', '{other}, thou metal wart!', 'Rex, I shall rust thee from the inside!'],
    biscuit: ['Biscuit, thou furry hearth-rug!', '{other}, thou slobbering good-for-nothing!', 'Biscuit, wee on another man\'s tyre!'],
  },
};
