// Tea-Time Tilly, rude banter: the Dame of the Ring Road, pearls on, gloves off. Impeccable manners for exactly one syllable, then a filthy mouth and a flask of something stronger.
export default {
  welcome: ['Good evening, you gorgeous little arseholes.', 'Do sit down, darlings. And shut your gobs.', 'Welcome, all. Do mind the pearls, they bite.'],
  select_me: ['Tilly? Darling, lovely. I will ruin them all.', 'A wise choice, dear. I am a menace in a flask.', 'Oh, how charming. You have chosen a violent granny.'],
  gp_win: ['The Cup is mine, darlings. Kiss my gloves, you tits.', 'Champion! I shall drink to that. And to your misery.', 'Victory! Do pass the gin and sod off.'],
  photo_finish: ['Goodness, that was close. My bloomers nearly flew off.', 'A photo finish, darlings. I nearly swore. Oh, I did.'],
  start: ['Pearls on, darlings. Gloves off. Fight!', 'Do behave. No, do not. Shite, do.', 'Engines, please. And do mind your knackers.', 'May the best woman win. That is me, you dears.'],
  go: ['Tally-ho, you pack of bastards!', 'Off we go, darlings. Mind the roundabouts. And the dead.', 'Go! Go! Go! Do not dawdle, you plonkers!'],
  rocket_start: ['Oh, marvellous! Take that, you slow sods.', 'Like a Labrador off a lead, darling.', 'A splendid start. Eat my exhaust, dears.'],
  bad_start: ['Oh, bugger. The bloody thing has stalled.', 'Stalled. Oh, sod it all, darling.', 'Well, that is bollocks, is it not?', 'Ooh. Do pardon me. I mean, fuck.'],
  boost: ['Oh, how thrilling! My knickers are flapping!', 'Faster! Faster! Bugger the pension!', 'Whee! Do you smell burning? Marvellous!', 'Turbo, darlings! Give it all you have!'],
  speed: ['Such speed, dears! My hair is ruined.', 'Flat out, and my teeth are loose. Splendid!', 'I shall never see the dentist again!'],
  drift: ['Sideways, darlings, like a Sunday roast.', 'Oh, I am sliding! I shall be sick! Tallyho!', 'Drifting! Quite unladylike. I adore it.'],
  mini_turbo: ['A little kick, darling. Lovely.', 'Whoosh! Naughty, naughty.'],
  max_charge: ['Maximum! Stand back, darlings, I am dangerous!', 'Fully loaded! Do mind the sherry!'],
  overtake: ['Do excuse me, {other}. Piss off.', 'Ever so sorry, {other}. Bugger off.', 'Mind my bumper, {other}, you clumsy tit.', 'Passing {other}. Smell you later, dear.', 'Oh, {other}, darling, what a view. Of my exhaust.', 'Ta-ta, {other}, you tiresome prat.'],
  overtaken: ['Oh, you vile little sod, {other}!', '{other}! Do not you dare, you rotten biscuit!', 'How dare you, {other}, you absolute melon!', 'I shall have you, {other}, on a plate with parsley!', '{other}, you gorgeous bastard. Do give it back.'],
  take_lead: ['First, darlings! Bow to your dame!', 'Leading! Do be a dear and lose.', 'The view is spectacular. The rest of you are not.'],
  lose_lead: ['Oh, bollocks, who took my lead?', 'Lost the lead, darlings. I shall be spiteful.', 'Somebody has stolen my lead. I shall find you.'],
  hit: ['Oh, bugger! My pearls!', 'Well, that was uncalled for, darling.', 'How very rude! Oh, sod it all!', 'Ow! Fuck. I mean, oh dear.', 'My hip! My lovely, lovely hip! Bastards!'],
  hit_by_item: ['Who threw that, darlings? I shall have them flogged!', 'Oh, you cheeky little bastards!', 'A dreadful manner of assault. I adore it.', 'Somebody is getting a stern letter. And a slap.'],
  hit_kernel_panic: ['A kernel panic! Oh, my nerves! Gin!', 'Well, that is a pure tragedy, bollocks.'],
  hit_bsod: ['Blue screen? Oh, how frightfully common!', 'Blue! The shame! Fetch the gin!'],
  hit_popups: ['Do shoo these adverts, darlings!', 'I am not buying a conservatory, you bounders!'],
  hit_shrink: ['I am tiny! Do not step on me, darlings!', 'Shrunk! How very inconvenient! Bollocks!'],
  hit_spill: ['A spillage! Oh, I shall shoot someone!', 'Whose tea is this?! Bring me a mop and a solicitor!'],
  hit_zeroday: ['A mine? How dare you, darling!', 'Zero-day! I shall sue the lot of you!'],
  hit_pigeon: ['A pigeon! On my beautiful hat!', 'The dreadful bird! I shall have it stuffed!'],
  item_get: ['Ooh, a little present! For someone\'s face!', 'Darling, what a lovely thing to break someone with.', 'Delightful. I shall use it on a tit.', 'Item! Lovely. Who wants to cry?'],
  item_use_attack: ['Do have this, {other}, you sweet little sod.', 'A gift, {other}! For your face!', 'Darling {other}, I am so sorry. No, I am not.', 'Take it, {other}, and sod off.', 'Incoming, darlings! Brace your bums!'],
  item_use_defence: ['Shield up, darlings! Do try it.', 'Protected! Kiss my gloves.', 'A little armour, dears. Do behave.'],
  item_hit_rival: ['Oh, got you, {other}! What a treat!', 'Direct hit, {other}, you delicious idiot!', 'Sorry, {other}. No, I am not, you tit.', 'Bullseye, {other}! Give me a biscuit!'],
  miss: ['Oh, bugger. I missed.', 'Shoddy work. Do not tell my agent.', 'Missed, darlings. Damn my eyes.'],
  dodged: ['Ha! Missed me, you dear little fools!', 'Nope, darlings! Try harder!', 'Dodged! I am spry. And furious.'],
  block: ['Blocked, darling. Not today.', 'Denied! Do sod off.', 'How rude, dear. Away with you!'],
  wall: ['Oh, goodness, the wall! Bastard wall!', 'Ooh! My chassis! My lovely chassis!', 'The wall attacked me! How uncouth!'],
  fall: ['Oh, I am falling, darlings! Dear me!', 'To the void! And I wore my good gloves!', 'Bugger. Falling. Sod it!', 'Down I go! Somebody catch my flask!'],
  respawn: ['Back, darlings, and twice as vicious.', 'Reincarnated! Do pour a gin!', 'I am back. And I am livid.'],
  offroad: ['Grass! My lovely shoes! Bugger!', 'How common, this sand. I shall lodge a complaint.', 'I am off the road, darlings. Do not look!'],
  jump: ['Flying, darlings! Fly, fly, fly!', 'Up, up! My bloomers are in orbit!', 'Airborne! I shall never land! Probably!'],
  near_miss: ['Goodness! I nearly soiled my bloomers!', 'Close call, darlings! My heart!', 'Oh, too near! Gin! Gin!'],
  wrong_way: ['Backwards? Darling, this is the fashion.', 'Wrong way! Oh, how excitingly rude!', 'Oh, dear. Wrong way. Do not tell anyone.'],
  last_place: ['Last? Darlings, I am practising humility. Bollocks.', 'The rear of the field. Not my favourite view.', 'Last! How unkind. I shall be spiteful.'],
  comeback: ['I rise, darlings! Like a furious soufflé!', 'Coming through, you tiresome sods!', 'A comeback! Do pour me a sherry!'],
  lap2: ['Lap two, darlings. Keep your knickers on.', 'Second lap! I am warming up. And drinking.'],
  final_lap: ['Final lap! Pearls off, darlings!', 'Last lap! Blood! Sherry! Blood!', 'Final lap, darlings. Shall we make it savage?'],
  finish_win: ['I won, darlings! Do kiss my ring. And my arse.', 'First! Bow down, you delightful little wretches!', 'Victory! Sherry, sherry, sherry!'],
  finish_podium: ['A podium, darlings! Pour the gin!', 'Top three! I shall celebrate and scowl.', 'Not first. But I look marvellous.'],
  finish_lose: ['I lost? How very dare it! Bollocks!', 'Defeat, darlings. I shall sulk in the garden.', 'Well, that was a bloody disaster.'],
  taunt: ['Faster, darlings! You drive like a retired vicar!', 'Do hurry up, you sweet little slugs!', 'Come along, you lot. My tea is going cold!', 'You are so slow, darling. Is it the gin?', 'I have had dreams faster than you.'],
  quip: ['I have buried three husbands and a Volvo. I shall bury you too.', 'Did anyone bring sandwiches? Or a weapon?', 'Do you think the audience can see my pearls?', 'Pearls are just tiny swears you wear round your neck.', 'I have not been this angry since 1974.', 'Is there a dog in the race? Does he pay tax?', 'If I win, I shall buy a larger hat.', 'The producers are watching. Hello, you lot of tits.', 'I have never loved anything as much as this gin.'],
  roast: ['{other}, darling, your steering is quite the tragedy.', 'Dear {other}, do learn to drive, you plonker.', '{other}, you drive like a sack of spanners.', 'Oh, {other}! I have seen better steering on a shopping trolley.', '{other}, darling, you are a disgrace to tarmac.'],
  bump: ['Oh, forgive me, {other}. Not really, you sod.', 'A little nudge, {other}. For your own good.', 'Budge, {other}, darling. Budge!'],
  bumped: ['{other}! You cheeky little bastard!', 'Do watch it, {other}, or I shall bite you.', 'Hands off, {other}, you grabby menace!'],
  perfect_jump: ['Perfect, darlings! Oh, marvellous!', 'Stuck the landing! Sherry!'],
  swap_item: ['Swapped, darling! What a lark!', 'Switch! Naughty, naughty!'],
  double_item: ['Two items! I am spoiled. And vicious.', 'Double the trouble, darlings!'],
  class_select: ['{class} Mbps, darlings? Faster than my knees.', '{class} Mbps! Lovely. Now watch me drive like a menace.', '{class} Mbps! I can hear my own heart.'],
  jump_vehicle: ['Jumped a lorry! Tally-ho, you sods!', 'Over the bus, darlings! Whee!'],
  vs: {
    marco: ['Marco, darling, do shut up and drive.', '{other}, you delightful pedagogue. Piss off.', 'Marco, your socks are a crime.'],
    subnet: ['Sir Subnet, you are a tin of beans with a plume.', '{other}, darling, your armour squeaks. Like a rusty gate.', 'Subnet! Take your lance elsewhere, you bore!'],
    lambda: ['Sadie, darling, do lower your voice. Or your invoice.', '{other}, you frenzied little gnat!', 'Sadie! You are a screaming invoice in a hoodie!'],
    packet: ['Pete, you are a delivery of shite.', '{other}, my darling, you are lost. And stupid.', 'Pete, darling, get a new stutter.'],
    carlos: ['Carlos, darling, wake up and take a bath.', '{other}! You are a sunburnt lime, dear!', 'Carlos, you lovely drunk. Move.'],
    rex: ['Rex, you handsome toaster. Go away.', '{other}, dear, stop shouting at me in code.', 'Rex, darling, have you tried being nice? No? Good.'],
    biscuit: ['Biscuit, darling, do not eat my hat!', '{other}! You lovely little bastard!', 'Biscuit, drop it. That is my handbag.'],
  },
};
