// One signature sound for every item (all 24 ids in config.js ITEMS), plus a hit sound for items that strike somebody, an end cue for timed
// items, and the item-slot sounds (roulette landing, swap, slots full). Everything is synthesised with the toolkit in synth.js: no samples.
//
// Naming (see ItemManager / AudioManager): `item-use-<id>` when the item is used, `item-hit-<id>` when it hits (or is applied to) a racer,
// `item-end-<id>` when a timed effect or shield ends. The recipes below are written at "natural" levels; each is then trimmed by
// `ITEM_LEVELS[name]` (sfx_levels.js, generated by `node tools/sfx_audition.mjs --calibrate`) so every one lands at the same loudness and peaks below -3 dBFS.
// Each sound is meant to be told apart with eyes closed: different pitch range, timbre and rhythm. Lengths are 0.15 to 1.2 s.
import { mtof, tone, burst, kick, drum, bell, noteToMidi } from './synth.js';
import { ITEM_LEVELS } from './sfx_levels.js';

const note = (n) => mtof(noteToMidi(n));
/** deterministic pseudo-random in 0..1 for step i (no Math.random: renders are reproducible) */
const rnd = (i, seed = 1) => { const x = Math.sin(i * 12.9898 + seed * 78.233) * 43758.5453; return x - Math.floor(x); };
/** rising / falling noise sweep */
const sweep = (c, out, t, { len = 0.3, f0 = 400, f1 = 3000, vol = 0.3, q = 1.2, a = 0.01, kind = 'white', type = 'bandpass' } = {}) =>
  burst(c, out, t, { dur: len, vol, type, freq: f0, freqEnd: f1, q, a, d: len * 0.4, s: 0.3, r: len * 0.45, kind });
/** a soft noise swell that builds then stops */
const swell = (c, out, t, { len = 0.4, f = 2000, f1 = 0, vol = 0.2, q = 1, type = 'bandpass', kind = 'white' } = {}) =>
  burst(c, out, t, { dur: len, vol, type, freq: f, freqEnd: f1, q, a: len * 0.7, d: len * 0.2, s: 0.4, r: len * 0.3, kind });
const click = (c, out, t, { vol = 0.3, f = 1700 } = {}) => {
  burst(c, out, t, { dur: 0.015, vol: vol * 0.6, type: 'highpass', freq: 2500, a: 0.0006 });
  tone(c, out, t, { wave: 'square', freq: f, dur: 0.008, a: 0.0005, d: 0.02, s: 0, r: 0.02, vol: vol * 0.5, cutoff: 3500 });
};

/** @type {Record<string, {dur: number, gap?: number, play: (c: BaseAudioContext, out: AudioNode, t: number, o: {pitch: number, vol: number}) => void}>} */
export const ITEM_RECIPES = {};
const r = (name, dur, play, gap = 0.08) => { ITEM_RECIPES[name] = { dur, gap, play }; };

// ---- the item slots ------------------------------------------------------------------------------------------------------------------

/** The roulette stops: a mechanical reel clunk and a short rising "ka-ching" so the result is clear before the item itself plays. */
r('roulette-land', 0.55, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.5, pitch: 70, punch: 160, decay: 0.16 });
  click(c, out, t + 0.01, { vol: 0.35, f: 1300 });
  [note('G5'), note('D6')].forEach((f, i) => bell(c, out, t + 0.1 + i * 0.07, { vol: 0.2, freq: f * o.pitch, decay: 0.28, ratio: 2.005 }));
}, 0.2);
/** Swap the two slots: two quick wooden ticks that cross, a tiny "shuffle". */
r('item-swap', 0.3, (c, out, t, o) => {
  tone(c, out, t, { wave: 'triangle', freq: 700 * o.pitch, glideFrom: 1000 * o.pitch, glideTime: 0.05, dur: 0.02, a: 0.001, d: 0.04, s: 0, r: 0.05, vol: 0.4 });
  tone(c, out, t + 0.09, { wave: 'triangle', freq: 1000 * o.pitch, glideFrom: 700 * o.pitch, glideTime: 0.05, dur: 0.02, a: 0.001, d: 0.04, s: 0, r: 0.05, vol: 0.4 });
  burst(c, out, t, { dur: 0.16, vol: 0.12, type: 'bandpass', freq: 3000, q: 1.5, a: 0.02, d: 0.05, s: 0.3, r: 0.08 });
}, 0.1);
/** Both slots full: a dull, low double "nope" (flat, muffled), nothing like a pickup. */
r('item-full', 0.38, (c, out, t, o) => {
  for (let i = 0; i < 2; i++) {
    tone(c, out, t + i * 0.13, { wave: 'square', freq: 196 * o.pitch, glideFrom: 215 * o.pitch, glideTime: 0.05, dur: 0.07, a: 0.003, d: 0.05, s: 0.5, r: 0.06, vol: 0.32, cutoff: 700 });
    tone(c, out, t + i * 0.13, { wave: 'sine', freq: 98 * o.pitch, dur: 0.07, a: 0.003, s: 0.6, r: 0.07, vol: 0.25 });
  }
}, 0.15);

// ---- speed and shields -----------------------------------------------------------------------------------------------------------------

/** Espresso: a slurp, a puff of steam and a short whoosh. */
r('item-use-espresso', 1.0, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.22, vol: 0.34, type: 'bandpass', freq: 500 * o.pitch, freqEnd: 1500 * o.pitch, q: 7, a: 0.02, d: 0.1, s: 0.5, r: 0.1 });
  tone(c, out, t, { wave: 'sine', freq: 740 * o.pitch, glideFrom: 280 * o.pitch, glideTime: 0.2, dur: 0.12, a: 0.01, s: 0.5, r: 0.1, vol: 0.16, vibrato: 60, vibRate: 16, vibDelay: 0 });
  burst(c, out, t + 0.12, { dur: 0.55, vol: 0.2, type: 'highpass', freq: 6500, q: 0.6, a: 0.04, d: 0.2, s: 0.4, r: 0.3 });
  sweep(c, out, t + 0.25, { len: 0.5, f0: 300, f1: 2800, vol: 0.38, q: 0.9, a: 0.1 });
});
/** Sudo: a deep power-chord stab, then a vault door: lock clicks, a heavy clunk and a hydraulic hiss. */
r('item-use-sudo', 1.1, (c, out, t, o) => {
  [73.4, 110, 146.8].forEach((f, i) => tone(c, out, t, { wave: 'sawtooth', freq: f * o.pitch, dur: 0.22, a: 0.004, d: 0.2, s: 0.4, r: 0.4, vol: 0.2, unison: 3, spread: 16, cutoff: 1500, cutoffEnd: 380, cutoffTime: 0.5, q: 2 + i }));
  kick(c, out, t, { vol: 0.6, pitch: 40, punch: 110, decay: 0.4 });
  click(c, out, t + 0.3, { vol: 0.3, f: 2300 }); click(c, out, t + 0.36, { vol: 0.3, f: 1900 });
  kick(c, out, t + 0.48, { vol: 0.55, pitch: 62, punch: 150, decay: 0.25 });
  bell(c, out, t + 0.48, { vol: 0.2, freq: 180 * o.pitch, decay: 0.55, ratio: 1.9 });
  burst(c, out, t + 0.58, { dur: 0.25, vol: 0.22, type: 'highpass', freq: 4200, q: 0.7, a: 0.02, d: 0.08, s: 0.4, r: 0.15 });
}, 0.3);
r('item-hit-sudo', 0.7, (c, out, t, o) => {            // the rival it shoulders aside: a heavy shunt and a metal clang
  kick(c, out, t, { vol: 0.65, pitch: 52, punch: 150, decay: 0.3 });
  tone(c, out, t, { wave: 'sawtooth', freq: 70 * o.pitch, glideFrom: 190 * o.pitch, glideTime: 0.2, dur: 0.12, a: 0.003, s: 0.4, r: 0.2, vol: 0.2, cutoff: 900 });
  bell(c, out, t + 0.02, { vol: 0.28, freq: 240 * o.pitch, decay: 0.4, ratio: 2.76 });
  burst(c, out, t, { dur: 0.18, vol: 0.3, type: 'bandpass', freq: 700, q: 0.8, a: 0.002 });
});
r('item-end-sudo', 0.5, (c, out, t, o) => {            // the power drains away
  tone(c, out, t, { wave: 'sawtooth', freq: 55 * o.pitch, glideFrom: 330 * o.pitch, glideTime: 0.35, dur: 0.2, a: 0.01, s: 0.6, r: 0.15, vol: 0.28, cutoff: 1200, cutoffEnd: 150 });
  click(c, out, t + 0.36, { vol: 0.25, f: 800 });
});
/** Firewall: a metallic shield shimmer over a low thrum. */
r('item-use-firewall', 0.9, (c, out, t, o) => {
  [note('G6'), note('D7'), note('G7')].forEach((f, i) => bell(c, out, t + i * 0.03, { vol: 0.16, freq: f * o.pitch, decay: 0.65, ratio: 2.005 }));
  tone(c, out, t, { wave: 'sine', freq: 2300 * o.pitch, dur: 0.4, a: 0.02, s: 0.5, r: 0.35, vol: 0.1, vibrato: 70, vibRate: 18, vibDelay: 0 });
  tone(c, out, t, { wave: 'sine', freq: 140 * o.pitch, dur: 0.3, a: 0.06, s: 0.7, r: 0.35, vol: 0.34 });
  swell(c, out, t, { len: 0.5, f: 6000, vol: 0.14, type: 'highpass' });
}, 0.3);
r('item-end-firewall', 0.7, (c, out, t, o) => {        // the shield shatters
  burst(c, out, t, { dur: 0.35, vol: 0.4, type: 'highpass', freq: 3500, q: 0.6, a: 0.001 });
  [note('G7'), note('D7'), note('G6'), note('D6')].forEach((f, i) => bell(c, out, t + i * 0.045, { vol: 0.2, freq: f * o.pitch, decay: 0.3, ratio: 2.76 }));
  kick(c, out, t, { vol: 0.35, pitch: 85, punch: 130, decay: 0.15 });
});
/** Fibre: a very fast data-burst zip. */
r('item-use-fibre', 0.5, (c, out, t, o) => {
  for (let i = 0; i < 16; i++) {
    const f = 900 * Math.pow(6, i / 15) * (0.9 + 0.2 * rnd(i, 3));
    tone(c, out, t + i * 0.022, { wave: 'square', freq: f * o.pitch, dur: 0.008, a: 0.0005, s: 0.5, r: 0.012, vol: 0.2, cutoff: 7000 });
  }
  tone(c, out, t, { wave: 'sine', freq: 4800 * o.pitch, glideFrom: 500 * o.pitch, glideTime: 0.3, dur: 0.1, a: 0.01, s: 0.6, r: 0.1, vol: 0.24 });
  burst(c, out, t, { dur: 0.3, vol: 0.2, type: 'highpass', freq: 5000, a: 0.005, d: 0.1, s: 0.3, r: 0.15 });
});
r('item-end-fibre', 0.4, (c, out, t, o) => {
  tone(c, out, t, { wave: 'sine', freq: 400 * o.pitch, glideFrom: 3600 * o.pitch, glideTime: 0.22, dur: 0.1, a: 0.005, s: 0.5, r: 0.1, vol: 0.28 });
  for (let i = 0; i < 4; i++) tone(c, out, t + i * 0.03, { wave: 'square', freq: (2200 - i * 450) * o.pitch, dur: 0.006, a: 0.0005, s: 0.5, r: 0.01, vol: 0.14, cutoff: 5000 });
});
/** Auto Scaling: a growth rumble that rises in pitch, ending in a springy boing. */
r('item-use-autoscale', 1.1, (c, out, t, o) => {
  tone(c, out, t, { wave: 'sawtooth', freq: 120 * o.pitch, glideFrom: 42 * o.pitch, glideTime: 0.8, dur: 0.8, a: 0.1, d: 0.3, s: 0.8, r: 0.15, vol: 0.26, cutoff: 1400, cutoffEnd: 260, cutoffTime: 0.8, q: 2.5, unison: 2, spread: 22 });
  tone(c, out, t, { wave: 'sine', freq: 140 * o.pitch, glideFrom: 55 * o.pitch, glideTime: 0.8, dur: 0.8, a: 0.1, s: 0.8, r: 0.15, vol: 0.34, vibrato: 40, vibRate: 7, vibDelay: 0 });
  burst(c, out, t, { dur: 0.9, vol: 0.42, type: 'lowpass', freq: 200, freqEnd: 900, q: 0.7, kind: 'brown', a: 0.5, d: 0.2, s: 0.5, r: 0.2 });
  tone(c, out, t + 0.82, { wave: 'triangle', freq: 520 * o.pitch, glideFrom: 200 * o.pitch, glideTime: 0.14, dur: 0.1, a: 0.004, s: 0.3, r: 0.2, vol: 0.28, vibrato: 90, vibRate: 12, vibDelay: 0 });
}, 0.4);
r('item-hit-autoscale', 0.5, (c, out, t, o) => {       // a squashed hazard: flat thud and a squeak
  kick(c, out, t, { vol: 0.6, pitch: 48, punch: 120, decay: 0.2 });
  tone(c, out, t + 0.03, { wave: 'triangle', freq: 130 * o.pitch, glideFrom: 520 * o.pitch, glideTime: 0.12, dur: 0.06, a: 0.002, s: 0, r: 0.1, vol: 0.3 });
});
r('item-end-autoscale', 0.55, (c, out, t, o) => {      // shrinking back: a falling whoop and a pop
  tone(c, out, t, { wave: 'sine', freq: 130 * o.pitch, glideFrom: 640 * o.pitch, glideTime: 0.35, dur: 0.15, a: 0.01, s: 0.6, r: 0.1, vol: 0.34, vibrato: 40, vibRate: 9, vibDelay: 0 });
  tone(c, out, t + 0.38, { wave: 'sine', freq: 900 * o.pitch, glideFrom: 240 * o.pitch, glideTime: 0.04, dur: 0.01, a: 0.001, s: 0, r: 0.06, vol: 0.4 });
});

// ---- shots, traps and hits ----------------------------------------------------------------------------------------------------------------

r('item-use-cable', 0.6, (c, out, t, o) => {           // a rope whip, then a metal clunk on the road
  sweep(c, out, t, { len: 0.12, f0: 400, f1: 2500, vol: 0.26, q: 1, a: 0.04 });
  burst(c, out, t + 0.11, { dur: 0.07, vol: 0.5, type: 'highpass', freq: 1500, freqEnd: 7000, q: 0.7, a: 0.0008 });
  tone(c, out, t + 0.11, { wave: 'sine', freq: 300 * o.pitch, glideFrom: 1800 * o.pitch, glideTime: 0.05, dur: 0.01, a: 0.0008, s: 0, r: 0.08, vol: 0.2 });
  kick(c, out, t + 0.25, { vol: 0.5, pitch: 80, punch: 190, decay: 0.2 });
  bell(c, out, t + 0.26, { vol: 0.2, freq: 330 * o.pitch, decay: 0.2, ratio: 1.7 });
});
r('item-hit-cable', 0.8, (c, out, t, o) => {           // tangled: falling thuds, a rattle and a whirl
  [160, 140, 118, 98].forEach((f, i) => tone(c, out, t + i * 0.07, { wave: 'triangle', freq: f * o.pitch, glideFrom: f * 1.8 * o.pitch, glideTime: 0.03, dur: 0.02, a: 0.001, s: 0, r: 0.08, vol: 0.4 }));
  sweep(c, out, t, { len: 0.4, f0: 1100, f1: 250, vol: 0.28, q: 1.2, a: 0.01 });
  tone(c, out, t + 0.1, { wave: 'sine', freq: 750 * o.pitch, glideFrom: 280 * o.pitch, glideTime: 0.4, dur: 0.3, a: 0.02, s: 0.5, r: 0.2, vol: 0.12, vibrato: 80, vibRate: 11, vibDelay: 0 });
  [0.3, 0.38, 0.45].forEach((d, i) => bell(c, out, t + d, { vol: 0.1, freq: (700 + i * 60) * o.pitch, decay: 0.12, ratio: 1.7 }));
});
/** Ping: a clean sonar blip with two fading echoes. */
r('item-use-ping', 0.95, (c, out, t, o) => {
  [[0, 0.42], [0.27, 0.2], [0.54, 0.09]].forEach(([d, v]) => {
    tone(c, out, t + d, { wave: 'sine', freq: 1320 * o.pitch, dur: 0.03, a: 0.004, d: 0.3, s: 0, r: 0.3, vol: v });
    tone(c, out, t + d, { wave: 'sine', freq: 3960 * o.pitch, dur: 0.01, a: 0.002, d: 0.08, s: 0, r: 0.1, vol: v * 0.2 });
  });
  burst(c, out, t, { dur: 0.01, vol: 0.12, type: 'highpass', freq: 4000, a: 0.0005 });
}, 0.2);
r('item-hit-ping', 0.5, (c, out, t, o) => {            // a bright tinkle and a small zap
  bell(c, out, t, { vol: 0.3, freq: 2093 * o.pitch, decay: 0.28, ratio: 2.4 });
  burst(c, out, t, { dur: 0.1, vol: 0.28, type: 'highpass', freq: 3000, freqEnd: 7500, q: 0.8, a: 0.001 });
  tone(c, out, t + 0.02, { wave: 'triangle', freq: 260 * o.pitch, glideFrom: 700 * o.pitch, glideTime: 0.1, dur: 0.05, a: 0.002, s: 0, r: 0.1, vol: 0.3 });
});
/** Traceroute: five hop blips climbing, the last one lands with a ring. */
r('item-use-traceroute', 0.75, (c, out, t, o) => {
  ['C5', 'D5', 'F5', 'A5', 'C6'].forEach((n, i) => {
    tone(c, out, t + i * 0.085, { wave: 'triangle', freq: note(n) * o.pitch, dur: 0.035, a: 0.002, d: 0.05, s: 0.2, r: 0.07, vol: 0.34 });
    click(c, out, t + i * 0.085, { vol: 0.1, f: 3000 });
  });
  bell(c, out, t + 0.44, { vol: 0.2, freq: note('C7') * o.pitch, decay: 0.3, ratio: 2.005 });
}, 0.2);
r('item-hit-traceroute', 0.6, (c, out, t, o) => {      // lock-on beeps then the thump
  [0, 0.09, 0.18].forEach((d, i) => tone(c, out, t + d, { wave: 'square', freq: 2000 * o.pitch, dur: i === 2 ? 0.1 : 0.04, a: 0.002, s: 0.8, r: 0.02, vol: 0.2, cutoff: 3500 }));
  kick(c, out, t + 0.3, { vol: 0.55, pitch: 55, punch: 140, decay: 0.2 });
  burst(c, out, t + 0.3, { dur: 0.15, vol: 0.25, type: 'bandpass', freq: 900, q: 0.9, a: 0.002 });
});
/** Kernel Panic: a two-tone alarm klaxon; the hit is glass crashing on the floor. */
r('item-use-kernel_panic', 0.9, (c, out, t, o) => {
  for (let i = 0; i < 6; i++) tone(c, out, t + i * 0.145, { wave: 'square', freq: (i % 2 ? 520 : 740) * o.pitch, dur: 0.12, a: 0.004, s: 0.9, r: 0.02, vol: 0.2, cutoff: 2400, q: 2 });
  tone(c, out, t, { wave: 'sawtooth', freq: 130 * o.pitch, dur: 0.85, a: 0.02, s: 0.5, r: 0.05, vol: 0.12, cutoff: 500 });
}, 0.5);
r('item-hit-kernel_panic', 1.2, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.5, pitch: 38, punch: 100, decay: 0.4 });
  burst(c, out, t, { dur: 0.5, vol: 0.4, type: 'highpass', freq: 3000, q: 0.5, a: 0.001, d: 0.1, s: 0.3, r: 0.3 });
  for (let i = 0; i < 16; i++) bell(c, out, t + 0.03 + i * 0.045 + rnd(i, 5) * 0.03, { vol: 0.1 + 0.08 * rnd(i, 7), freq: (2400 + rnd(i, 9) * 4800) * o.pitch, decay: 0.12 + rnd(i, 4) * 0.12, ratio: 2.76 });
}, 0.3);
/** Sniffer: two sniffs and a snuffle; the hit is the steal: a swoop and a pocketed "bloop". */
r('item-use-sniffer', 0.7, (c, out, t, o) => {
  [0, 0.16].forEach((d, i) => burst(c, out, t + d, { dur: 0.1, vol: 0.34, type: 'bandpass', freq: (2600 + i * 600) * o.pitch, freqEnd: 4200, q: 1.6, a: 0.045, d: 0.04, s: 0.2, r: 0.04 }));
  tone(c, out, t + 0.33, { wave: 'triangle', freq: 150 * o.pitch, glideFrom: 210 * o.pitch, glideTime: 0.2, dur: 0.15, a: 0.02, s: 0.5, r: 0.1, vol: 0.22, vibrato: 100, vibRate: 15, vibDelay: 0 });
  burst(c, out, t + 0.33, { dur: 0.2, vol: 0.14, type: 'bandpass', freq: 1800, q: 2, a: 0.03, d: 0.08, s: 0.3, r: 0.1 });
}, 0.3);
r('item-hit-sniffer', 0.6, (c, out, t, o) => {
  tone(c, out, t, { wave: 'sine', freq: 1500 * o.pitch, glideFrom: 280 * o.pitch, glideTime: 0.14, dur: 0.07, a: 0.004, s: 0.5, r: 0.08, vol: 0.3 });
  tone(c, out, t + 0.17, { wave: 'sine', freq: 300 * o.pitch, glideFrom: 900 * o.pitch, glideTime: 0.07, dur: 0.02, a: 0.002, s: 0, r: 0.1, vol: 0.4 });
  bell(c, out, t + 0.26, { vol: 0.18, freq: 1760 * o.pitch, decay: 0.2, ratio: 2.005 });
});
/** BSOD: a dissonant low chord, a burst of static and three falling error beeps. */
r('item-use-bsod', 0.9, (c, out, t, o) => {
  [73.4, 103.8, 130.8].forEach((f) => tone(c, out, t, { wave: 'sawtooth', freq: f * o.pitch, dur: 0.4, a: 0.01, d: 0.2, s: 0.7, r: 0.3, vol: 0.2, cutoff: 800, unison: 2, spread: 18 }));
  [0, 0.12, 0.24].forEach((d) => burst(c, out, t + d, { dur: 0.08, vol: 0.28, type: 'highpass', freq: 1500, a: 0.001 }));
  [880, 660, 440].forEach((f, i) => tone(c, out, t + 0.5 + i * 0.11, { wave: 'square', freq: f * o.pitch, dur: 0.08, a: 0.003, s: 0.8, r: 0.02, vol: 0.14, cutoff: 2600 }));
}, 0.4);
r('item-hit-bsod', 0.6, (c, out, t, o) => {            // static crackle and a dying hum
  for (let i = 0; i < 7; i++) burst(c, out, t + i * 0.05 + rnd(i, 2) * 0.03, { dur: 0.04, vol: 0.2 + 0.15 * rnd(i, 3), type: 'highpass', freq: 1200 + rnd(i, 6) * 2500, a: 0.0006 });
  tone(c, out, t, { wave: 'sawtooth', freq: 45 * o.pitch, glideFrom: 140 * o.pitch, glideTime: 0.4, dur: 0.2, a: 0.004, s: 0.6, r: 0.15, vol: 0.28, cutoff: 500 });
});
/** Spill: a splash, a plop and droplets; the hit is a squeaky slip. */
r('item-use-spill', 0.6, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.3, vol: 0.4, type: 'bandpass', freq: 1500, freqEnd: 650, q: 0.8, a: 0.004, d: 0.08, s: 0.3, r: 0.18 });
  tone(c, out, t, { wave: 'sine', freq: 170 * o.pitch, glideFrom: 520 * o.pitch, glideTime: 0.07, dur: 0.02, a: 0.002, s: 0, r: 0.1, vol: 0.4 });
  [[0.11, 1250], [0.17, 1550], [0.24, 950]].forEach(([d, f]) => tone(c, out, t + d, { wave: 'sine', freq: f * o.pitch, glideFrom: f * 0.6 * o.pitch, glideTime: 0.025, dur: 0.01, a: 0.001, s: 0, r: 0.04, vol: 0.16 }));
});
r('item-hit-spill', 0.7, (c, out, t, o) => {
  tone(c, out, t, { wave: 'triangle', freq: 1500 * o.pitch, glideFrom: 420 * o.pitch, glideTime: 0.2, dur: 0.2, a: 0.01, s: 0.6, r: 0.15, vol: 0.28, vibrato: 60, vibRate: 10, vibDelay: 0 });
  tone(c, out, t + 0.3, { wave: 'triangle', freq: 380 * o.pitch, glideFrom: 1300 * o.pitch, glideTime: 0.16, dur: 0.08, a: 0.005, s: 0.5, r: 0.1, vol: 0.24 });
  sweep(c, out, t + 0.05, { len: 0.4, f0: 900, f1: 400, vol: 0.2, q: 1, a: 0.04 });
});
/** Zero-Day: tick, tick, beep to arm it, a thunk as it drops; the hit is a big boom with shrapnel. */
r('item-use-zeroday', 0.7, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.5, pitch: 70, punch: 140, decay: 0.12 });
  click(c, out, t + 0.14, { vol: 0.5, f: 1750 }); click(c, out, t + 0.32, { vol: 0.5, f: 1450 });
  tone(c, out, t + 0.5, { wave: 'sine', freq: 1000 * o.pitch, dur: 0.12, a: 0.003, s: 0.9, r: 0.03, vol: 0.3 });
});
r('item-hit-zeroday', 1.2, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.9, pitch: 30, punch: 100, decay: 0.8 });
  burst(c, out, t, { dur: 1.0, vol: 0.45, type: 'lowpass', freq: 2600, freqEnd: 90, q: 0.7, a: 0.002, d: 0.3, s: 0.3, r: 0.6 });
  tone(c, out, t, { wave: 'sine', freq: 36 * o.pitch, dur: 0.3, a: 0.004, s: 0.7, r: 0.7, vol: 0.5 });
  for (let i = 0; i < 9; i++) bell(c, out, t + 0.14 + i * 0.08 + rnd(i, 8) * 0.05, { vol: 0.07, freq: (1500 + rnd(i, 3) * 3500) * o.pitch, decay: 0.1, ratio: 2.4 });
}, 0.3);
/** Pods: three pods spin around the kart, panned left, centre, right (twice). Their end is three falling plucks. */
r('item-use-pods', 0.9, (c, out, t, o) => {
  for (let k = 0; k < 6; k++) {
    const f = [220, 277.2, 329.6][k % 3] * (k > 2 ? 1.5 : 1) * o.pitch, pan = [-0.8, 0, 0.8][k % 3];
    tone(c, out, t + k * 0.13, { wave: 'sine', freq: f, glideFrom: f * 0.9, glideTime: 0.06, dur: 0.07, a: 0.01, d: 0.1, s: 0.5, r: 0.1, vol: 0.32, pan, vibrato: 40, vibRate: 14, vibDelay: 0 });
    tone(c, out, t + k * 0.13, { wave: 'triangle', freq: f * 2, dur: 0.05, a: 0.01, s: 0.3, r: 0.08, vol: 0.08, pan });
  }
}, 0.3);
r('item-hit-pods', 0.5, (c, out, t, o) => {            // a launched pod hits: plink and a small bang
  bell(c, out, t, { vol: 0.28, freq: 880 * o.pitch, decay: 0.2, ratio: 2.005 });
  kick(c, out, t, { vol: 0.4, pitch: 70, punch: 160, decay: 0.12 });
  burst(c, out, t, { dur: 0.12, vol: 0.28, type: 'bandpass', freq: 1800, q: 1, a: 0.001 });
});
r('item-end-pods', 0.45, (c, out, t, o) => {
  [660, 495, 330].forEach((f, i) => tone(c, out, t + i * 0.1, { wave: 'sine', freq: f * o.pitch, dur: 0.02, a: 0.002, d: 0.08, s: 0, r: 0.1, vol: 0.34 }));
});
/** Force Push: an air-blast thump; the hit is a smack and a whoosh away. */
r('item-use-forcepush', 0.6, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.75, pitch: 52, punch: 130, decay: 0.28 });
  burst(c, out, t, { dur: 0.3, vol: 0.45, type: 'bandpass', freq: 250, freqEnd: 1800, q: 1, a: 0.006, d: 0.1, s: 0.3, r: 0.18 });
  burst(c, out, t + 0.02, { dur: 0.1, vol: 0.25, type: 'highpass', freq: 3500, a: 0.002 });
  tone(c, out, t, { wave: 'sine', freq: 70 * o.pitch, glideFrom: 160 * o.pitch, glideTime: 0.2, dur: 0.1, a: 0.003, s: 0.6, r: 0.2, vol: 0.3 });
}, 0.2);
r('item-hit-forcepush', 0.55, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.05, vol: 0.5, type: 'bandpass', freq: 1400, q: 1.2, a: 0.0008 });
  tone(c, out, t, { wave: 'sine', freq: 120 * o.pitch, glideFrom: 420 * o.pitch, glideTime: 0.1, dur: 0.05, a: 0.002, s: 0, r: 0.1, vol: 0.4 });
  sweep(c, out, t + 0.04, { len: 0.3, f0: 1900, f1: 300, vol: 0.26, q: 1.4, a: 0.01 });
});
/** Pigeon: coo-roo-coo and a flurry of wing flaps; the hit is a wet splat. */
r('item-use-pigeon', 0.8, (c, out, t, o) => {
  [[0, 440, 0.13], [0.17, 400, 0.09], [0.29, 470, 0.2]].forEach(([d, f, l]) => {
    tone(c, out, t + d, { wave: 'sine', freq: f * o.pitch, glideFrom: f * 1.18 * o.pitch, glideTime: l * 0.7, dur: l, a: 0.02, s: 0.8, r: 0.05, vol: 0.34, vibrato: 45, vibRate: 11, vibDelay: 0 });
    tone(c, out, t + d, { wave: 'triangle', freq: f * 2 * o.pitch, dur: l, a: 0.03, s: 0.5, r: 0.05, vol: 0.06 });
  });
  for (let i = 0; i < 7; i++) burst(c, out, t + 0.5 + i * (0.05 - i * 0.003), { dur: 0.05, vol: 0.2 + 0.05 * Math.sin(i / 6 * Math.PI) * 2, type: 'bandpass', freq: 650 + 90 * (i % 2), q: 1, a: 0.004 });
});
r('item-hit-pigeon', 0.6, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.3, vol: 0.5, type: 'lowpass', freq: 2200, freqEnd: 250, q: 1.1, a: 0.002, d: 0.1, s: 0.3, r: 0.15 });
  tone(c, out, t, { wave: 'sine', freq: 70 * o.pitch, glideFrom: 300 * o.pitch, glideTime: 0.1, dur: 0.05, a: 0.002, s: 0.3, r: 0.12, vol: 0.4 });
  burst(c, out, t + 0.12, { dur: 0.12, vol: 0.2, type: 'bandpass', freq: 700, q: 2, a: 0.002 });
});
/** Capacitor: a rising charging whine, a bright ding at the sweet spot, a crackling zap on release and a buzz on the hit. */
r('item-charge', 1.2, (c, out, t, o) => {
  tone(c, out, t, { wave: 'sawtooth', freq: 1800 * o.pitch, glideFrom: 140 * o.pitch, glideTime: 1.1, dur: 1.1, a: 0.05, s: 1, r: 0.06, vol: 0.2, cutoff: 500, cutoffEnd: 5000, cutoffTime: 1.1, q: 4, vibrato: 25, vibRate: 9, vibDelay: 0.3 });
  tone(c, out, t, { wave: 'sine', freq: 900 * o.pitch, glideFrom: 70 * o.pitch, glideTime: 1.1, dur: 1.1, a: 0.05, s: 1, r: 0.06, vol: 0.16 });
  for (let i = 0; i < 9; i++) click(c, out, t + 0.3 + i * (0.1 - i * 0.006), { vol: 0.12 + i * 0.015, f: 2500 });
}, 0.5);
r('item-charge-ready', 0.5, (c, out, t, o) => {
  bell(c, out, t, { vol: 0.34, freq: 1976 * o.pitch, decay: 0.45, ratio: 2.005 });
  bell(c, out, t + 0.07, { vol: 0.22, freq: 2637 * o.pitch, decay: 0.4, ratio: 2.005 });
  burst(c, out, t, { dur: 0.25, vol: 0.14, type: 'highpass', freq: 7000, a: 0.002, d: 0.08, s: 0.2, r: 0.15 });
}, 0.3);
r('item-use-capacitor', 0.7, (c, out, t, o) => {
  tone(c, out, t, { wave: 'sawtooth', freq: 160 * o.pitch, glideFrom: 3400 * o.pitch, glideTime: 0.22, dur: 0.1, a: 0.002, s: 0.5, r: 0.12, vol: 0.2, cutoff: 5000 });
  for (let i = 0; i < 8; i++) burst(c, out, t + i * 0.03 + rnd(i, 4) * 0.015, { dur: 0.03, vol: 0.28, type: 'highpass', freq: 2000 + rnd(i, 2) * 4000, a: 0.0005 });
  kick(c, out, t, { vol: 0.5, pitch: 60, punch: 150, decay: 0.2 });
}, 0.2);
r('item-hit-capacitor', 0.6, (c, out, t, o) => {       // an electric buzz
  tone(c, out, t, { wave: 'square', freq: 110 * o.pitch, dur: 0.3, a: 0.003, s: 0.8, r: 0.15, vol: 0.22, cutoff: 1800, vibrato: 120, vibRate: 40, vibDelay: 0 });
  for (let i = 0; i < 7; i++) burst(c, out, t + i * 0.04, { dur: 0.03, vol: 0.2, type: 'highpass', freq: 2500 + rnd(i, 5) * 3500, a: 0.0006 });
});
/** Legacy server: an old fan spins up, hard-drive seek clicks, a clunk and a POST beep; the hit is a metal clang and a disk grind. */
r('item-use-legacy', 1.0, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.55, vol: 0.3, type: 'bandpass', freq: 320, q: 2, a: 0.25, d: 0.15, s: 0.5, r: 0.2, kind: 'pink' });
  tone(c, out, t, { wave: 'sawtooth', freq: 95 * o.pitch, dur: 0.5, a: 0.2, s: 0.6, r: 0.15, vol: 0.12, cutoff: 320, vibrato: 35, vibRate: 24, vibDelay: 0 });
  [[0.12, 1100], [0.16, 900], [0.22, 1300]].forEach(([d, f]) => click(c, out, t + d, { vol: 0.3, f }));
  kick(c, out, t + 0.34, { vol: 0.5, pitch: 78, punch: 140, decay: 0.18 });
  bell(c, out, t + 0.34, { vol: 0.2, freq: 150 * o.pitch, decay: 0.25, ratio: 2.2 });
  tone(c, out, t + 0.62, { wave: 'sine', freq: 1000 * o.pitch, dur: 0.14, a: 0.004, s: 0.9, r: 0.03, vol: 0.24 });
}, 0.3);
r('item-hit-legacy', 0.9, (c, out, t, o) => {
  bell(c, out, t, { vol: 0.34, freq: 140 * o.pitch, decay: 0.6, ratio: 1.9 });
  bell(c, out, t, { vol: 0.2, freq: 223 * o.pitch, decay: 0.5, ratio: 2.76 });
  kick(c, out, t, { vol: 0.55, pitch: 50, punch: 150, decay: 0.3 });
  burst(c, out, t, { dur: 0.15, vol: 0.3, type: 'bandpass', freq: 1200, q: 0.8, a: 0.001 });
  tone(c, out, t + 0.2, { wave: 'sawtooth', freq: 85 * o.pitch, dur: 0.3, a: 0.01, s: 0.6, r: 0.1, vol: 0.12, cutoff: 500, vibrato: 90, vibRate: 30, vibDelay: 0 });
});
r('item-end-legacy', 0.7, (c, out, t, o) => {          // the fan spins down
  tone(c, out, t, { wave: 'sawtooth', freq: 40 * o.pitch, glideFrom: 160 * o.pitch, glideTime: 0.55, dur: 0.3, a: 0.01, s: 0.7, r: 0.2, vol: 0.2, cutoff: 400, cutoffEnd: 100, vibrato: 30, vibRate: 12, vibDelay: 0 });
  click(c, out, t + 0.5, { vol: 0.25, f: 900 });
});
/** Cron Job: a sizzling fuse ticking faster and faster, then a "hot potato" zip as it is passed on; the hit is the fizzle-bang. */
r('item-use-cronjob', 0.9, (c, out, t, o) => {
  burst(c, out, t, { dur: 0.7, vol: 0.14, type: 'highpass', freq: 5500, q: 0.7, a: 0.01, d: 0.3, s: 0.6, r: 0.2 });
  [0, 0.18, 0.33, 0.45, 0.55, 0.63, 0.7].forEach((d, i) => click(c, out, t + d, { vol: 0.28 + i * 0.03, f: 1500 * o.pitch }));
  tone(c, out, t + 0.74, { wave: 'sine', freq: 3200 * o.pitch, glideFrom: 400 * o.pitch, glideTime: 0.1, dur: 0.04, a: 0.003, s: 0.6, r: 0.06, vol: 0.3 });
}, 0.3);
r('item-hit-cronjob', 0.8, (c, out, t, o) => {
  kick(c, out, t, { vol: 0.6, pitch: 62, punch: 150, decay: 0.2 });
  burst(c, out, t, { dur: 0.25, vol: 0.4, type: 'bandpass', freq: 1800, freqEnd: 500, q: 0.8, a: 0.001, d: 0.06, s: 0.3, r: 0.12 });
  burst(c, out, t + 0.15, { dur: 0.45, vol: 0.18, type: 'highpass', freq: 5000, freqEnd: 3000, q: 0.7, a: 0.005, d: 0.2, s: 0.3, r: 0.25 });
  tone(c, out, t + 0.05, { wave: 'sine', freq: 200 * o.pitch, glideFrom: 800 * o.pitch, glideTime: 0.2, dur: 0.06, a: 0.002, s: 0.4, r: 0.1, vol: 0.22 });
});
/** Outage: a power-down groan with a relay clunk; the hit (shrunk) is a squeak. */
r('item-use-outage', 1.1, (c, out, t, o) => {
  click(c, out, t, { vol: 0.35, f: 900 }); kick(c, out, t, { vol: 0.4, pitch: 60, punch: 120, decay: 0.15 });
  tone(c, out, t + 0.04, { wave: 'sawtooth', freq: 36 * o.pitch, glideFrom: 210 * o.pitch, glideTime: 0.85, dur: 0.8, a: 0.02, s: 0.8, r: 0.2, vol: 0.28, cutoff: 900, cutoffEnd: 100, cutoffTime: 0.9, q: 2 });
  tone(c, out, t + 0.04, { wave: 'sine', freq: 50 * o.pitch, dur: 0.8, a: 0.05, s: 0.8, r: 0.2, vol: 0.26 });
  click(c, out, t + 0.96, { vol: 0.3, f: 700 });
}, 0.5);
r('item-hit-outage', 0.4, (c, out, t, o) => {
  tone(c, out, t, { wave: 'triangle', freq: 420 * o.pitch, glideFrom: 1900 * o.pitch, glideTime: 0.22, dur: 0.12, a: 0.003, s: 0.5, r: 0.08, vol: 0.34, vibrato: 60, vibRate: 15, vibDelay: 0 });
  tone(c, out, t + 0.27, { wave: 'sine', freq: 1200 * o.pitch, glideFrom: 300 * o.pitch, glideTime: 0.03, dur: 0.01, a: 0.001, s: 0, r: 0.05, vol: 0.3 });
});
/** Zoomies end: the panting slows and a small whimper. */
r('item-end-zoomies', 0.6, (c, out, t, o) => {
  [0, 0.14, 0.3].forEach((d, i) => burst(c, out, t + d, { dur: 0.09, vol: 0.28, type: 'bandpass', freq: 2400 - i * 300, q: 1.4, a: 0.01, r: 0.05 }));
  tone(c, out, t + 0.4, { wave: 'triangle', freq: 520 * o.pitch, glideFrom: 880 * o.pitch, glideTime: 0.18, dur: 0.12, a: 0.01, s: 0.5, r: 0.1, vol: 0.26, vibrato: 60, vibRate: 10, vibDelay: 0 });
});

/** Sounds defined in sfx.js (Biscuit's items) that get the same loudness trim. */
export const BISCUIT_ITEM_SFX = ['item-use-woof', 'item-hit-woof', 'item-use-poo', 'item-hit-poo', 'item-use-zoomies', 'item-use-fetch', 'item-hit-fetch', 'item-catch'];

/** Every sound that takes a loudness trim from sfx_levels.js. */
export const levelledNames = () => [...Object.keys(ITEM_RECIPES), ...BISCUIT_ITEM_SFX];

const clipCurves = new WeakMap();
/** A fixed soft clipper: y = 0.7 tanh(x / 0.7). Unity gain for small signals, never above 0.7, identical in every browser (unlike a compressor's makeup gain). */
function softClip(c) {
  let curve = clipCurves.get(c);
  if (!curve) {
    curve = new Float32Array(2049);
    for (let i = 0; i < curve.length; i++) { const x = (i / 1024 - 1) * 2; curve[i] = 0.7 * Math.tanh(x / 0.7); }   // input range -2..2
    clipCurves.set(c, curve);
  }
  const sh = c.createWaveShaper(); sh.curve = curve;
  return sh;
}

/** Wrap a play function: scaled by the calibrated trim (and the caller's vol), then soft-clipped so nothing can pass 0.7 (about -3 dBFS). */
export const withTrim = (name, play) => (c, out, t, o) => {
  const g = c.createGain(); g.gain.value = (ITEM_LEVELS[name] ?? 1) * o.vol;
  const sh = softClip(c);
  g.connect(sh); sh.connect(out);
  play(c, g, t, { pitch: o.pitch, vol: 1 });
};

/** Register every recipe in the SFX table (`def` is sfx.js's definer) and trim the Biscuit sounds already there. */
export function installItemSfx(SFX, def) {
  for (const [name, rc] of Object.entries(ITEM_RECIPES)) {
    def(name, rc.dur, withTrim(name, rc.play), { gap: rc.gap });
    SFX[name].raw = rc.play;
  }
  for (const name of BISCUIT_ITEM_SFX) {
    const d = SFX[name];
    if (!d) continue;
    d.raw = d.play;
    d.play = withTrim(name, d.raw);
  }
}
