// Audition / calibrate the item sounds without a browser.
//   node tools/sfx_audition.mjs [--out DIR] [--only substr] [--raw]   render each item sound to DIR/<name>.wav and print peak / loudness / length
//   node tools/sfx_audition.mjs --calibrate                           measure the untrimmed recipes and rewrite src/audio/sfx_levels.js
// A table row flags CLIP when the peak reaches full scale and QUIET/LOUD when the loudness is more than 1.5 dB from the common target.
import fs from 'node:fs';
import path from 'node:path';
import { SFX } from '../src/audio/sfx.js';
import { levelledNames } from '../src/audio/sfx_items.js';
import { ITEM_LEVELS } from '../src/audio/sfx_levels.js';
import { renderDef, measure, toDb, writeWav, CALIBRATION } from './sfx_lib.mjs';

const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const val = (n, d) => (args.includes(n) ? args[args.indexOf(n) + 1] : d);
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const names = levelledNames().filter((n) => !val('--only', '') || n.includes(val('--only', '')));

if (flag('--calibrate')) {
  const levels = {};
  for (const name of levelledNames()) {
    // trims go through a soft clipper, so find them iteratively: render with the trim in place, correct by the loudness error
    let trim = 1;
    for (let i = 0; i < 6; i++) {
      ITEM_LEVELS[name] = trim;
      const m = measure(await renderDef(SFX[name]));
      trim *= 10 ** (CALIBRATION.targetDb / 20) / Math.max(m.rms, 1e-6);
      trim = Math.min(trim, 12);
    }
    levels[name] = Math.round(trim * 1000) / 1000; ITEM_LEVELS[name] = levels[name];
    const m = measure(await renderDef(SFX[name]));
    console.log(name.padEnd(26), `trim ${levels[name]}  loud ${toDb(m.rms).toFixed(1)} dB  peak ${toDb(m.peak).toFixed(1)} dB`);
  }
  const body = Object.entries(levels).map(([k, v]) => `  '${k}': ${v},`).join('\n');
  fs.writeFileSync(path.join(root, 'src/audio/sfx_levels.js'), `// GENERATED by \`node tools/sfx_audition.mjs --calibrate\` (do not edit by hand): per-sound trim so every item sound lands at the same loudness\n// (loudest 150 ms RMS ${CALIBRATION.targetDb} dBFS; a soft clipper holds peaks under 0.7).\nexport const ITEM_LEVELS = {\n${body}\n};\n`);
  console.log('wrote src/audio/sfx_levels.js');
} else {
  const out = val('--out', path.join(root, 'shots/sfx'));
  fs.mkdirSync(out, { recursive: true });
  console.log('name'.padEnd(26), 'peak dB  loud dB  audible s  flags');
  let bad = 0;
  for (const name of names) {
    const r = await renderDef(SFX[name], { raw: flag('--raw') });
    const m = measure(r);
    writeWav(path.join(out, `${name}.wav`), r);
    const flags = [m.nan ? 'NaN' : '', m.peak >= 0.999 ? 'CLIP' : '', Math.abs(toDb(m.rms) - CALIBRATION.targetDb) > 1.5 ? (toDb(m.rms) < CALIBRATION.targetDb ? 'QUIET' : 'LOUD') : ''].filter(Boolean).join(' ');
    if (flags) bad++;
    console.log(name.padEnd(26), toDb(m.peak).toFixed(1).padStart(6), toDb(m.rms).toFixed(1).padStart(8), m.seconds.toFixed(2).padStart(9), ' ', flags);
  }
  console.log(`${names.length} sounds written to ${out}; ${bad} flagged`);
}
